// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// M3ChangePasswordRequest m3 change password request
// swagger:model m3ChangePasswordRequest
type M3ChangePasswordRequest struct {

	// User's new password to set
	NewPassword string `json:"new_password,omitempty"`

	// User's current password
	OldPassword string `json:"old_password,omitempty"`
}

// Validate validates this m3 change password request
func (m *M3ChangePasswordRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *M3ChangePasswordRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *M3ChangePasswordRequest) UnmarshalBinary(b []byte) error {
	var res M3ChangePasswordRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
