// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// M3ForgotPasswordRequest m3 forgot password request
// swagger:model m3ForgotPasswordRequest
type M3ForgotPasswordRequest struct {

	// company
	Company string `json:"company,omitempty"`

	// email
	Email string `json:"email,omitempty"`
}

// Validate validates this m3 forgot password request
func (m *M3ForgotPasswordRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *M3ForgotPasswordRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *M3ForgotPasswordRequest) UnmarshalBinary(b []byte) error {
	var res M3ForgotPasswordRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
