// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// M3InviteRequest Sends an invite to signup a new user or reset a user's password
// swagger:model m3InviteRequest
type M3InviteRequest struct {

	// Email of the new user who will receive the invitation email
	Email string `json:"email,omitempty"`

	// Name of new user to be created
	Name string `json:"name,omitempty"`
}

// Validate validates this m3 invite request
func (m *M3InviteRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *M3InviteRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *M3InviteRequest) UnmarshalBinary(b []byte) error {
	var res M3InviteRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
