// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// M3ListServiceAccountsResponse Request a list of ServiceAccounts on the tenant account
// swagger:model m3ListServiceAccountsResponse
type M3ListServiceAccountsResponse struct {

	// list of resulting ServiceAccounts
	ServiceAccounts []*M3ServiceAccount `json:"service_accounts"`

	// number of ServiceAccounts on the tenant account
	Total int32 `json:"total,omitempty"`
}

// Validate validates this m3 list service accounts response
func (m *M3ListServiceAccountsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateServiceAccounts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *M3ListServiceAccountsResponse) validateServiceAccounts(formats strfmt.Registry) error {

	if swag.IsZero(m.ServiceAccounts) { // not required
		return nil
	}

	for i := 0; i < len(m.ServiceAccounts); i++ {
		if swag.IsZero(m.ServiceAccounts[i]) { // not required
			continue
		}

		if m.ServiceAccounts[i] != nil {
			if err := m.ServiceAccounts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("service_accounts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *M3ListServiceAccountsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *M3ListServiceAccountsResponse) UnmarshalBinary(b []byte) error {
	var res M3ListServiceAccountsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
