// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// M3LoginRequest m3 login request
// swagger:model m3LoginRequest
type M3LoginRequest struct {

	// Company short name
	Company string `json:"company,omitempty"`

	// User's email
	Email string `json:"email,omitempty"`

	// User's password
	Password string `json:"password,omitempty"`
}

// Validate validates this m3 login request
func (m *M3LoginRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *M3LoginRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *M3LoginRequest) UnmarshalBinary(b []byte) error {
	var res M3LoginRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
