// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// M3MetricsDayUsage Usage per day
// swagger:model m3MetricsDayUsage
type M3MetricsDayUsage struct {

	// time
	Time string `json:"time,omitempty"`

	// usage
	Usage string `json:"usage,omitempty"`
}

// Validate validates this m3 metrics day usage
func (m *M3MetricsDayUsage) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *M3MetricsDayUsage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *M3MetricsDayUsage) UnmarshalBinary(b []byte) error {
	var res M3MetricsDayUsage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
