// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// M3MultiAddPermissionToSAsRequest m3 multi add permission to s as request
// swagger:model m3MultiAddPermissionToSAsRequest
type M3MultiAddPermissionToSAsRequest struct {

	// id
	ID string `json:"id,omitempty"`

	// service account id
	ServiceAccountID []string `json:"service_account_id"`
}

// Validate validates this m3 multi add permission to s as request
func (m *M3MultiAddPermissionToSAsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *M3MultiAddPermissionToSAsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *M3MultiAddPermissionToSAsRequest) UnmarshalBinary(b []byte) error {
	var res M3MultiAddPermissionToSAsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
