// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// M3MultiAddPermissionToSAsResponse m3 multi add permission to s as response
// swagger:model m3MultiAddPermissionToSAsResponse
type M3MultiAddPermissionToSAsResponse struct {

	// error
	Error string `json:"error,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this m3 multi add permission to s as response
func (m *M3MultiAddPermissionToSAsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *M3MultiAddPermissionToSAsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *M3MultiAddPermissionToSAsResponse) UnmarshalBinary(b []byte) error {
	var res M3MultiAddPermissionToSAsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
