// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// M3RegisterAccountRequest Message containing details of the Tenant Admin and the tenant that is going to be created
// swagger:model m3RegisterAccountRequest
type M3RegisterAccountRequest struct {

	// company
	Company string `json:"company,omitempty"`

	// company short name
	CompanyShortName string `json:"company_short_name,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// full name
	FullName string `json:"full_name,omitempty"`

	// password
	Password string `json:"password,omitempty"`
}

// Validate validates this m3 register account request
func (m *M3RegisterAccountRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *M3RegisterAccountRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *M3RegisterAccountRequest) UnmarshalBinary(b []byte) error {
	var res M3RegisterAccountRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
