// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// M3SetPasswordRequest Used for Signing Up a new User and Resetting a Password
// swagger:model m3SetPasswordRequest
type M3SetPasswordRequest struct {

	// User's password to set
	Password string `json:"password,omitempty"`

	// url token
	URLToken string `json:"url_token,omitempty"`
}

// Validate validates this m3 set password request
func (m *M3SetPasswordRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *M3SetPasswordRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *M3SetPasswordRequest) UnmarshalBinary(b []byte) error {
	var res M3SetPasswordRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
