// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// M3UpdateServiceAccountRequest m3 update service account request
// swagger:model m3UpdateServiceAccountRequest
type M3UpdateServiceAccountRequest struct {

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// permission ids
	PermissionIds []string `json:"permission_ids"`
}

// Validate validates this m3 update service account request
func (m *M3UpdateServiceAccountRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *M3UpdateServiceAccountRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *M3UpdateServiceAccountRequest) UnmarshalBinary(b []byte) error {
	var res M3UpdateServiceAccountRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
