// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Kubernetes Cloud
// Copyright (c) 2020 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package admin_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateTenantHandlerFunc turns a function with the right signature into a create tenant handler
type CreateTenantHandlerFunc func(CreateTenantParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateTenantHandlerFunc) Handle(params CreateTenantParams) middleware.Responder {
	return fn(params)
}

// CreateTenantHandler interface for that can handle valid create tenant params
type CreateTenantHandler interface {
	Handle(CreateTenantParams) middleware.Responder
}

// NewCreateTenant creates a new http.Handler for the create tenant operation
func NewCreateTenant(ctx *middleware.Context, handler CreateTenantHandler) *CreateTenant {
	return &CreateTenant{Context: ctx, Handler: handler}
}

/*CreateTenant swagger:route POST /tenants AdminAPI createTenant

Create Tenant

*/
type CreateTenant struct {
	Context *middleware.Context
	Handler CreateTenantHandler
}

func (o *CreateTenant) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateTenantParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
