// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Kubernetes Cloud
// Copyright (c) 2020 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package admin_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/m3/models"
)

// ListClustersOKCode is the HTTP code returned for type ListClustersOK
const ListClustersOKCode int = 200

/*ListClustersOK A successful response.

swagger:response listClustersOK
*/
type ListClustersOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListClustersResponse `json:"body,omitempty"`
}

// NewListClustersOK creates ListClustersOK with default headers values
func NewListClustersOK() *ListClustersOK {

	return &ListClustersOK{}
}

// WithPayload adds the payload to the list clusters o k response
func (o *ListClustersOK) WithPayload(payload *models.ListClustersResponse) *ListClustersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list clusters o k response
func (o *ListClustersOK) SetPayload(payload *models.ListClustersResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListClustersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ListClustersDefault Generic error response.

swagger:response listClustersDefault
*/
type ListClustersDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListClustersDefault creates ListClustersDefault with default headers values
func NewListClustersDefault(code int) *ListClustersDefault {
	if code <= 0 {
		code = 500
	}

	return &ListClustersDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list clusters default response
func (o *ListClustersDefault) WithStatusCode(code int) *ListClustersDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list clusters default response
func (o *ListClustersDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list clusters default response
func (o *ListClustersDefault) WithPayload(payload *models.Error) *ListClustersDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list clusters default response
func (o *ListClustersDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListClustersDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
