// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Kubernetes Cloud
// Copyright (c) 2020 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package admin_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/m3/models"
)

// StartMirroringCreatedCode is the HTTP code returned for type StartMirroringCreated
const StartMirroringCreatedCode int = 201

/*StartMirroringCreated A successful response.

swagger:response startMirroringCreated
*/
type StartMirroringCreated struct {

	/*
	  In: Body
	*/
	Payload *models.StartMirroringResponse `json:"body,omitempty"`
}

// NewStartMirroringCreated creates StartMirroringCreated with default headers values
func NewStartMirroringCreated() *StartMirroringCreated {

	return &StartMirroringCreated{}
}

// WithPayload adds the payload to the start mirroring created response
func (o *StartMirroringCreated) WithPayload(payload *models.StartMirroringResponse) *StartMirroringCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the start mirroring created response
func (o *StartMirroringCreated) SetPayload(payload *models.StartMirroringResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StartMirroringCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*StartMirroringDefault Generic error response.

swagger:response startMirroringDefault
*/
type StartMirroringDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewStartMirroringDefault creates StartMirroringDefault with default headers values
func NewStartMirroringDefault(code int) *StartMirroringDefault {
	if code <= 0 {
		code = 500
	}

	return &StartMirroringDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the start mirroring default response
func (o *StartMirroringDefault) WithStatusCode(code int) *StartMirroringDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the start mirroring default response
func (o *StartMirroringDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the start mirroring default response
func (o *StartMirroringDefault) WithPayload(payload *models.Error) *StartMirroringDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the start mirroring default response
func (o *StartMirroringDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StartMirroringDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
