FROM kindest/node:v1.15.3

RUN mkdir -p /mnt/disk1 && mkdir -p /mnt/disk2 && mkdir -p /mnt/disk3 && mkdir -p /mnt/disk4 && mkdir -p /mnt/disk5 && mkdir -p /mnt/disk6 && mkdir -p /mnt/disk7 && mkdir -p /mnt/disk8
