# This is the setup for MinIO Operator taken from https://github.com/minio/minio-operator
!~operator_file~!
# M3 setup
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: m3-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: m3-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: m3-sa
    namespace: default
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: client
---
apiVersion: v1
kind: Service
metadata:
  name: m3
  labels:
    name: m3
spec:
  ports:
    - port: 8787
      name: http
    - port: 8443
      name: https
  selector:
    app: m3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m3
  template:
    metadata:
      labels:
        app: m3
    spec:
      serviceAccountName: m3-sa
      containers:
        - name: m3
          image: minio/m3:edge
          imagePullPolicy: "IfNotPresent"
          args:
            - /m3
            - controller
          envFrom:
            - configMapRef:
                name: m3-env
          ports:
            - containerPort: 8787
              name: http
            - containerPort: 8443
              name: https
