// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/m3/portal/models"
)

// AssignPermissionsToServiceAccountOKCode is the HTTP code returned for type AssignPermissionsToServiceAccountOK
const AssignPermissionsToServiceAccountOKCode int = 200

/*AssignPermissionsToServiceAccountOK A successful response.

swagger:response assignPermissionsToServiceAccountOK
*/
type AssignPermissionsToServiceAccountOK struct {

	/*
	  In: Body
	*/
	Payload models.M3Empty `json:"body,omitempty"`
}

// NewAssignPermissionsToServiceAccountOK creates AssignPermissionsToServiceAccountOK with default headers values
func NewAssignPermissionsToServiceAccountOK() *AssignPermissionsToServiceAccountOK {

	return &AssignPermissionsToServiceAccountOK{}
}

// WithPayload adds the payload to the assign permissions to service account o k response
func (o *AssignPermissionsToServiceAccountOK) WithPayload(payload models.M3Empty) *AssignPermissionsToServiceAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the assign permissions to service account o k response
func (o *AssignPermissionsToServiceAccountOK) SetPayload(payload models.M3Empty) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AssignPermissionsToServiceAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
