// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ChangeBucketAccessControlHandlerFunc turns a function with the right signature into a change bucket access control handler
type ChangeBucketAccessControlHandlerFunc func(ChangeBucketAccessControlParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ChangeBucketAccessControlHandlerFunc) Handle(params ChangeBucketAccessControlParams) middleware.Responder {
	return fn(params)
}

// ChangeBucketAccessControlHandler interface for that can handle valid change bucket access control params
type ChangeBucketAccessControlHandler interface {
	Handle(ChangeBucketAccessControlParams) middleware.Responder
}

// NewChangeBucketAccessControl creates a new http.Handler for the change bucket access control operation
func NewChangeBucketAccessControl(ctx *middleware.Context, handler ChangeBucketAccessControlHandler) *ChangeBucketAccessControl {
	return &ChangeBucketAccessControl{Context: ctx, Handler: handler}
}

/*ChangeBucketAccessControl swagger:route POST /api/v1/buckets/{name}/access_control PublicAPI changeBucketAccessControl

Change Bucket access control between private and public.

*/
type ChangeBucketAccessControl struct {
	Context *middleware.Context
	Handler ChangeBucketAccessControlHandler
}

func (o *ChangeBucketAccessControl) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewChangeBucketAccessControlParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
