// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/m3/portal/models"
)

// CreateServiceAccountOKCode is the HTTP code returned for type CreateServiceAccountOK
const CreateServiceAccountOKCode int = 200

/*CreateServiceAccountOK A successful response.

swagger:response createServiceAccountOK
*/
type CreateServiceAccountOK struct {

	/*
	  In: Body
	*/
	Payload *models.M3CreateServiceAccountResponse `json:"body,omitempty"`
}

// NewCreateServiceAccountOK creates CreateServiceAccountOK with default headers values
func NewCreateServiceAccountOK() *CreateServiceAccountOK {

	return &CreateServiceAccountOK{}
}

// WithPayload adds the payload to the create service account o k response
func (o *CreateServiceAccountOK) WithPayload(payload *models.M3CreateServiceAccountResponse) *CreateServiceAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create service account o k response
func (o *CreateServiceAccountOK) SetPayload(payload *models.M3CreateServiceAccountResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateServiceAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
