// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/m3/portal/models"
)

// EnableUserOKCode is the HTTP code returned for type EnableUserOK
const EnableUserOKCode int = 200

/*EnableUserOK A successful response.

swagger:response enableUserOK
*/
type EnableUserOK struct {

	/*
	  In: Body
	*/
	Payload *models.M3UserActionResponse `json:"body,omitempty"`
}

// NewEnableUserOK creates EnableUserOK with default headers values
func NewEnableUserOK() *EnableUserOK {

	return &EnableUserOK{}
}

// WithPayload adds the payload to the enable user o k response
func (o *EnableUserOK) WithPayload(payload *models.M3UserActionResponse) *EnableUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the enable user o k response
func (o *EnableUserOK) SetPayload(payload *models.M3UserActionResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *EnableUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
