// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ForgotPasswordHandlerFunc turns a function with the right signature into a forgot password handler
type ForgotPasswordHandlerFunc func(ForgotPasswordParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ForgotPasswordHandlerFunc) Handle(params ForgotPasswordParams) middleware.Responder {
	return fn(params)
}

// ForgotPasswordHandler interface for that can handle valid forgot password params
type ForgotPasswordHandler interface {
	Handle(ForgotPasswordParams) middleware.Responder
}

// NewForgotPassword creates a new http.Handler for the forgot password operation
func NewForgotPassword(ctx *middleware.Context, handler ForgotPasswordHandler) *ForgotPassword {
	return &ForgotPassword{Context: ctx, Handler: handler}
}

/*ForgotPassword swagger:route POST /api/v1/users/forgot_password PublicAPI forgotPassword

Sends an email to set a new password

*/
type ForgotPassword struct {
	Context *middleware.Context
	Handler ForgotPasswordHandler
}

func (o *ForgotPassword) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewForgotPasswordParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
