// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/m3/portal/models"
)

// ForgotPasswordOKCode is the HTTP code returned for type ForgotPasswordOK
const ForgotPasswordOKCode int = 200

/*ForgotPasswordOK A successful response.

swagger:response forgotPasswordOK
*/
type ForgotPasswordOK struct {

	/*
	  In: Body
	*/
	Payload models.M3Empty `json:"body,omitempty"`
}

// NewForgotPasswordOK creates ForgotPasswordOK with default headers values
func NewForgotPasswordOK() *ForgotPasswordOK {

	return &ForgotPasswordOK{}
}

// WithPayload adds the payload to the forgot password o k response
func (o *ForgotPasswordOK) WithPayload(payload models.M3Empty) *ForgotPasswordOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the forgot password o k response
func (o *ForgotPasswordOK) SetPayload(payload models.M3Empty) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ForgotPasswordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
