// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/m3/portal/models"
)

// InfoPermissionOKCode is the HTTP code returned for type InfoPermissionOK
const InfoPermissionOKCode int = 200

/*InfoPermissionOK A successful response.

swagger:response infoPermissionOK
*/
type InfoPermissionOK struct {

	/*
	  In: Body
	*/
	Payload *models.M3Permission `json:"body,omitempty"`
}

// NewInfoPermissionOK creates InfoPermissionOK with default headers values
func NewInfoPermissionOK() *InfoPermissionOK {

	return &InfoPermissionOK{}
}

// WithPayload adds the payload to the info permission o k response
func (o *InfoPermissionOK) WithPayload(payload *models.M3Permission) *InfoPermissionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the info permission o k response
func (o *InfoPermissionOK) SetPayload(payload *models.M3Permission) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InfoPermissionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
