// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// InfoUserHandlerFunc turns a function with the right signature into a info user handler
type InfoUserHandlerFunc func(InfoUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn InfoUserHandlerFunc) Handle(params InfoUserParams) middleware.Responder {
	return fn(params)
}

// InfoUserHandler interface for that can handle valid info user params
type InfoUserHandler interface {
	Handle(InfoUserParams) middleware.Responder
}

// NewInfoUser creates a new http.Handler for the info user operation
func NewInfoUser(ctx *middleware.Context, handler InfoUserHandler) *InfoUser {
	return &InfoUser{Context: ctx, Handler: handler}
}

/*InfoUser swagger:route GET /api/v1/users/{id} PublicAPI infoUser

Get details for an individual user

*/
type InfoUser struct {
	Context *middleware.Context
	Handler InfoUserHandler
}

func (o *InfoUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewInfoUserParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
