// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListServiceAccountsHandlerFunc turns a function with the right signature into a list service accounts handler
type ListServiceAccountsHandlerFunc func(ListServiceAccountsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListServiceAccountsHandlerFunc) Handle(params ListServiceAccountsParams) middleware.Responder {
	return fn(params)
}

// ListServiceAccountsHandler interface for that can handle valid list service accounts params
type ListServiceAccountsHandler interface {
	Handle(ListServiceAccountsParams) middleware.Responder
}

// NewListServiceAccounts creates a new http.Handler for the list service accounts operation
func NewListServiceAccounts(ctx *middleware.Context, handler ListServiceAccountsHandler) *ListServiceAccounts {
	return &ListServiceAccounts{Context: ctx, Handler: handler}
}

/*ListServiceAccounts swagger:route GET /api/v1/service_accounts PublicAPI listServiceAccounts

List Service Accounts

*/
type ListServiceAccounts struct {
	Context *middleware.Context
	Handler ListServiceAccountsHandler
}

func (o *ListServiceAccounts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListServiceAccountsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
