// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListBucketsHandlerFunc turns a function with the right signature into a list buckets handler
type ListBucketsHandlerFunc func(ListBucketsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListBucketsHandlerFunc) Handle(params ListBucketsParams) middleware.Responder {
	return fn(params)
}

// ListBucketsHandler interface for that can handle valid list buckets params
type ListBucketsHandler interface {
	Handle(ListBucketsParams) middleware.Responder
}

// NewListBuckets creates a new http.Handler for the list buckets operation
func NewListBuckets(ctx *middleware.Context, handler ListBucketsHandler) *ListBuckets {
	return &ListBuckets{Context: ctx, Handler: handler}
}

/*ListBuckets swagger:route GET /api/v1/buckets PublicAPI listBuckets

List Buckets

*/
type ListBuckets struct {
	Context *middleware.Context
	Handler ListBucketsHandler
}

func (o *ListBuckets) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListBucketsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
