// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/m3/portal/models"
)

// ListPermissionsOKCode is the HTTP code returned for type ListPermissionsOK
const ListPermissionsOKCode int = 200

/*ListPermissionsOK A successful response.

swagger:response listPermissionsOK
*/
type ListPermissionsOK struct {

	/*
	  In: Body
	*/
	Payload *models.M3ListPermissionsResponse `json:"body,omitempty"`
}

// NewListPermissionsOK creates ListPermissionsOK with default headers values
func NewListPermissionsOK() *ListPermissionsOK {

	return &ListPermissionsOK{}
}

// WithPayload adds the payload to the list permissions o k response
func (o *ListPermissionsOK) WithPayload(payload *models.M3ListPermissionsResponse) *ListPermissionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list permissions o k response
func (o *ListPermissionsOK) SetPayload(payload *models.M3ListPermissionsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPermissionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
