// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/m3/portal/models"
)

// MetricsOKCode is the HTTP code returned for type MetricsOK
const MetricsOKCode int = 200

/*MetricsOK A successful response.

swagger:response metricsOK
*/
type MetricsOK struct {

	/*
	  In: Body
	*/
	Payload *models.M3MetricsResponse `json:"body,omitempty"`
}

// NewMetricsOK creates MetricsOK with default headers values
func NewMetricsOK() *MetricsOK {

	return &MetricsOK{}
}

// WithPayload adds the payload to the metrics o k response
func (o *MetricsOK) WithPayload(payload *models.M3MetricsResponse) *MetricsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the metrics o k response
func (o *MetricsOK) SetPayload(payload *models.M3MetricsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MetricsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
