// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/m3/portal/models"
)

// RegisterTenantOKCode is the HTTP code returned for type RegisterTenantOK
const RegisterTenantOKCode int = 200

/*RegisterTenantOK A successful response.

swagger:response registerTenantOK
*/
type RegisterTenantOK struct {

	/*
	  In: Body
	*/
	Payload *models.M3RegisterAccountResponse `json:"body,omitempty"`
}

// NewRegisterTenantOK creates RegisterTenantOK with default headers values
func NewRegisterTenantOK() *RegisterTenantOK {

	return &RegisterTenantOK{}
}

// WithPayload adds the payload to the register tenant o k response
func (o *RegisterTenantOK) WithPayload(payload *models.M3RegisterAccountResponse) *RegisterTenantOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register tenant o k response
func (o *RegisterTenantOK) SetPayload(payload *models.M3RegisterAccountResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterTenantOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
