// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RemovePermissionHandlerFunc turns a function with the right signature into a remove permission handler
type RemovePermissionHandlerFunc func(RemovePermissionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RemovePermissionHandlerFunc) Handle(params RemovePermissionParams) middleware.Responder {
	return fn(params)
}

// RemovePermissionHandler interface for that can handle valid remove permission params
type RemovePermissionHandler interface {
	Handle(RemovePermissionParams) middleware.Responder
}

// NewRemovePermission creates a new http.Handler for the remove permission operation
func NewRemovePermission(ctx *middleware.Context, handler RemovePermissionHandler) *RemovePermission {
	return &RemovePermission{Context: ctx, Handler: handler}
}

/*RemovePermission swagger:route DELETE /api/v1/permissions/{id} PublicAPI removePermission

Remove a Permission

*/
type RemovePermission struct {
	Context *middleware.Context
	Handler RemovePermissionHandler
}

func (o *RemovePermission) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRemovePermissionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
