// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/m3/portal/models"
)

// UpdateServiceAccountOKCode is the HTTP code returned for type UpdateServiceAccountOK
const UpdateServiceAccountOKCode int = 200

/*UpdateServiceAccountOK A successful response.

swagger:response updateServiceAccountOK
*/
type UpdateServiceAccountOK struct {

	/*
	  In: Body
	*/
	Payload *models.M3InfoServiceAccountResponse `json:"body,omitempty"`
}

// NewUpdateServiceAccountOK creates UpdateServiceAccountOK with default headers values
func NewUpdateServiceAccountOK() *UpdateServiceAccountOK {

	return &UpdateServiceAccountOK{}
}

// WithPayload adds the payload to the update service account o k response
func (o *UpdateServiceAccountOK) WithPayload(payload *models.M3InfoServiceAccountResponse) *UpdateServiceAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update service account o k response
func (o *UpdateServiceAccountOK) SetPayload(payload *models.M3InfoServiceAccountResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateServiceAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
