// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/m3/portal/models"
)

// UpdatePermissionOKCode is the HTTP code returned for type UpdatePermissionOK
const UpdatePermissionOKCode int = 200

/*UpdatePermissionOK A successful response.

swagger:response updatePermissionOK
*/
type UpdatePermissionOK struct {

	/*
	  In: Body
	*/
	Payload *models.M3Permission `json:"body,omitempty"`
}

// NewUpdatePermissionOK creates UpdatePermissionOK with default headers values
func NewUpdatePermissionOK() *UpdatePermissionOK {

	return &UpdatePermissionOK{}
}

// WithPayload adds the payload to the update permission o k response
func (o *UpdatePermissionOK) WithPayload(payload *models.M3Permission) *UpdatePermissionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update permission o k response
func (o *UpdatePermissionOK) SetPayload(payload *models.M3Permission) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdatePermissionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
