// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/m3/portal/models"
)

// UserWhoAmIOKCode is the HTTP code returned for type UserWhoAmIOK
const UserWhoAmIOKCode int = 200

/*UserWhoAmIOK A successful response.

swagger:response userWhoAmIOK
*/
type UserWhoAmIOK struct {

	/*
	  In: Body
	*/
	Payload *models.M3WhoAmIResponse `json:"body,omitempty"`
}

// NewUserWhoAmIOK creates UserWhoAmIOK with default headers values
func NewUserWhoAmIOK() *UserWhoAmIOK {

	return &UserWhoAmIOK{}
}

// WithPayload adds the payload to the user who am i o k response
func (o *UserWhoAmIOK) WithPayload(payload *models.M3WhoAmIResponse) *UserWhoAmIOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user who am i o k response
func (o *UserWhoAmIOK) SetPayload(payload *models.M3WhoAmIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserWhoAmIOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
