// Code generated by go-swagger; DO NOT EDIT.

package public_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UserAddInviteHandlerFunc turns a function with the right signature into a user add invite handler
type UserAddInviteHandlerFunc func(UserAddInviteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UserAddInviteHandlerFunc) Handle(params UserAddInviteParams) middleware.Responder {
	return fn(params)
}

// UserAddInviteHandler interface for that can handle valid user add invite params
type UserAddInviteHandler interface {
	Handle(UserAddInviteParams) middleware.Responder
}

// NewUserAddInvite creates a new http.Handler for the user add invite operation
func NewUserAddInvite(ctx *middleware.Context, handler UserAddInviteHandler) *UserAddInvite {
	return &UserAddInvite{Context: ctx, Handler: handler}
}

/*UserAddInvite swagger:route POST /api/v1/users/add_invite PublicAPI userAddInvite

Sends an email invitation for sign up

*/
type UserAddInvite struct {
	Context *middleware.Context
	Handler UserAddInviteHandler
}

func (o *UserAddInvite) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUserAddInviteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
