# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nginx-config
# data:
#   nginx.conf: |
#     your config
#     comes here
#     like this
#   other.conf: |
#     second file
#     contents
# ---
apiVersion: v1
kind: Service
metadata:
  name: nginx-resolver
  labels:
    name: nginx-1
spec:
  ports:
    - port: 80
      name: http
  clusterIP: None
  selector:
    app: nginx-resolver
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-resolver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-resolver
        tenant: nginx-1
    spec:
      nodeSelector:
        kubernetes.io/hostname: m3cluster-worker3
      containers:
        - name: nginx-resolver-1
          image: nginx
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: "nginx-configuration"
              mountPath: "/etc/nginx/nginx.conf"
              subPath: "nginx.conf"
          # volumeMounts:
          #   - name: secret-volume
          #     readOnly: true
          #     mountPath: "/etc/nginx"

      volumes:
        - name: nginx-configuration
          configMap:
            name: nginx-configuration
        # - name: secret-volume
        #   secret:
        #     secretName: nginx-configuration
