---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: m3-user
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: m3-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: m3-user
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: m3
  labels:
    name: m3
spec:
  ports:
    - port: 50051
      name: public-grpc
    - port: 50052
      name: private-grpc
  selector:
    app: m3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m3
  template:
    metadata:
      labels:
        app: m3
    spec:
      serviceAccountName: m3-user
      containers:
        - name: m3
          image: minio/m3:dev
          imagePullPolicy: "IfNotPresent"
          args:
            - /m3
            - service
          env:
            - name: ADMIN_NAME
              value: <DEV_NAME>
            - name: ADMIN_EMAIL
              value: <DEV_EMAIL>
            - name: DB_HOSTNAME
              value: postgres.m3
            - name: MAIL_ACCOUNT
              value: <ACCOUNT>
            - name: MAIL_SERVER
              value: <SERVER>
            - name: MAIL_PASSWORD
              value: <PASSWORD>
            - name: APP_URL
              value: localhost:3000
          ports:
            - containerPort: 50051
              name: public-grpc
            - containerPort: 50052
              name: private-grpc
