---
apiVersion: v1
kind: Service
metadata:
  name: m3
  labels:
    name: m3
spec:
  ports:
    - port: 50051
      name: public-grpc
    - port: 50052
      name: private-grpc
  selector:
    app: m3
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: m3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: m3
    spec:
      containers:
        - name: m3
          image: minio/m3:dev
          imagePullPolicy: "IfNotPresent"
          args:
            - /m3
            - service
          env:
            - name: DB_HOSTNAME
              value: postgres.m3
            - name: MAIL_ACCOUNT
              value: <ACCOUNT>
            - name: MAIL_SERVER
              value: <SERVER>
            - name: MAIL_PASSWORD
              value: <PASSWORD>
          ports:
            - containerPort: 50051
              name: public-grpc
            - containerPort: 50052
              name: private-grpc
