---
apiVersion: v1
kind: Service
metadata:
  name: m3-portal-frontend
  labels:
    name: m3-portal-frontend
spec:
  ports:
    - port: 80
      name: webserver
  selector:
    app: m3-portal-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m3-portal-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m3-portal-frontend
  template:
    metadata:
      labels:
        app: m3-portal-frontend
    spec:
      containers:
        - name: m3-portal-frontend
          image: minio/m3-portal-frontend:dev
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
              name: webserver
