// Code generated by protoc-gen-go. DO NOT EDIT.
// source: private_api.proto

package m3

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdminEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminEmpty) Reset()         { *m = AdminEmpty{} }
func (m *AdminEmpty) String() string { return proto.CompactTextString(m) }
func (*AdminEmpty) ProtoMessage()    {}
func (*AdminEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{0}
}

func (m *AdminEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminEmpty.Unmarshal(m, b)
}
func (m *AdminEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminEmpty.Marshal(b, m, deterministic)
}
func (m *AdminEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminEmpty.Merge(m, src)
}
func (m *AdminEmpty) XXX_Size() int {
	return xxx_messageInfo_AdminEmpty.Size(m)
}
func (m *AdminEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_AdminEmpty proto.InternalMessageInfo

type TenantAddRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ShortName            string   `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserEmail            string   `protobuf:"bytes,4,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantAddRequest) Reset()         { *m = TenantAddRequest{} }
func (m *TenantAddRequest) String() string { return proto.CompactTextString(m) }
func (*TenantAddRequest) ProtoMessage()    {}
func (*TenantAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{1}
}

func (m *TenantAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantAddRequest.Unmarshal(m, b)
}
func (m *TenantAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantAddRequest.Marshal(b, m, deterministic)
}
func (m *TenantAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantAddRequest.Merge(m, src)
}
func (m *TenantAddRequest) XXX_Size() int {
	return xxx_messageInfo_TenantAddRequest.Size(m)
}
func (m *TenantAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TenantAddRequest proto.InternalMessageInfo

func (m *TenantAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TenantAddRequest) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *TenantAddRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *TenantAddRequest) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

type TenantAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantAddResponse) Reset()         { *m = TenantAddResponse{} }
func (m *TenantAddResponse) String() string { return proto.CompactTextString(m) }
func (*TenantAddResponse) ProtoMessage()    {}
func (*TenantAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{2}
}

func (m *TenantAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantAddResponse.Unmarshal(m, b)
}
func (m *TenantAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantAddResponse.Marshal(b, m, deterministic)
}
func (m *TenantAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantAddResponse.Merge(m, src)
}
func (m *TenantAddResponse) XXX_Size() int {
	return xxx_messageInfo_TenantAddResponse.Size(m)
}
func (m *TenantAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TenantAddResponse proto.InternalMessageInfo

type TenantBucketAddRequest struct {
	Tenant               string   `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	BucketName           string   `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantBucketAddRequest) Reset()         { *m = TenantBucketAddRequest{} }
func (m *TenantBucketAddRequest) String() string { return proto.CompactTextString(m) }
func (*TenantBucketAddRequest) ProtoMessage()    {}
func (*TenantBucketAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{3}
}

func (m *TenantBucketAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantBucketAddRequest.Unmarshal(m, b)
}
func (m *TenantBucketAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantBucketAddRequest.Marshal(b, m, deterministic)
}
func (m *TenantBucketAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantBucketAddRequest.Merge(m, src)
}
func (m *TenantBucketAddRequest) XXX_Size() int {
	return xxx_messageInfo_TenantBucketAddRequest.Size(m)
}
func (m *TenantBucketAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantBucketAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TenantBucketAddRequest proto.InternalMessageInfo

func (m *TenantBucketAddRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *TenantBucketAddRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

type TenantBucketAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantBucketAddResponse) Reset()         { *m = TenantBucketAddResponse{} }
func (m *TenantBucketAddResponse) String() string { return proto.CompactTextString(m) }
func (*TenantBucketAddResponse) ProtoMessage()    {}
func (*TenantBucketAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{4}
}

func (m *TenantBucketAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantBucketAddResponse.Unmarshal(m, b)
}
func (m *TenantBucketAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantBucketAddResponse.Marshal(b, m, deterministic)
}
func (m *TenantBucketAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantBucketAddResponse.Merge(m, src)
}
func (m *TenantBucketAddResponse) XXX_Size() int {
	return xxx_messageInfo_TenantBucketAddResponse.Size(m)
}
func (m *TenantBucketAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantBucketAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TenantBucketAddResponse proto.InternalMessageInfo

type TenantPermissionAddRequest struct {
	Tenant               string   `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Effect               string   `protobuf:"bytes,4,opt,name=effect,proto3" json:"effect,omitempty"`
	Resources            []string `protobuf:"bytes,5,rep,name=resources,proto3" json:"resources,omitempty"`
	Actions              []string `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantPermissionAddRequest) Reset()         { *m = TenantPermissionAddRequest{} }
func (m *TenantPermissionAddRequest) String() string { return proto.CompactTextString(m) }
func (*TenantPermissionAddRequest) ProtoMessage()    {}
func (*TenantPermissionAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{5}
}

func (m *TenantPermissionAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantPermissionAddRequest.Unmarshal(m, b)
}
func (m *TenantPermissionAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantPermissionAddRequest.Marshal(b, m, deterministic)
}
func (m *TenantPermissionAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantPermissionAddRequest.Merge(m, src)
}
func (m *TenantPermissionAddRequest) XXX_Size() int {
	return xxx_messageInfo_TenantPermissionAddRequest.Size(m)
}
func (m *TenantPermissionAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantPermissionAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TenantPermissionAddRequest proto.InternalMessageInfo

func (m *TenantPermissionAddRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *TenantPermissionAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TenantPermissionAddRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TenantPermissionAddRequest) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

func (m *TenantPermissionAddRequest) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *TenantPermissionAddRequest) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

type TenantPermissionAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantPermissionAddResponse) Reset()         { *m = TenantPermissionAddResponse{} }
func (m *TenantPermissionAddResponse) String() string { return proto.CompactTextString(m) }
func (*TenantPermissionAddResponse) ProtoMessage()    {}
func (*TenantPermissionAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{6}
}

func (m *TenantPermissionAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantPermissionAddResponse.Unmarshal(m, b)
}
func (m *TenantPermissionAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantPermissionAddResponse.Marshal(b, m, deterministic)
}
func (m *TenantPermissionAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantPermissionAddResponse.Merge(m, src)
}
func (m *TenantPermissionAddResponse) XXX_Size() int {
	return xxx_messageInfo_TenantPermissionAddResponse.Size(m)
}
func (m *TenantPermissionAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantPermissionAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TenantPermissionAddResponse proto.InternalMessageInfo

type TenantPermissionListRequest struct {
	Tenant               string   `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantPermissionListRequest) Reset()         { *m = TenantPermissionListRequest{} }
func (m *TenantPermissionListRequest) String() string { return proto.CompactTextString(m) }
func (*TenantPermissionListRequest) ProtoMessage()    {}
func (*TenantPermissionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{7}
}

func (m *TenantPermissionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantPermissionListRequest.Unmarshal(m, b)
}
func (m *TenantPermissionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantPermissionListRequest.Marshal(b, m, deterministic)
}
func (m *TenantPermissionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantPermissionListRequest.Merge(m, src)
}
func (m *TenantPermissionListRequest) XXX_Size() int {
	return xxx_messageInfo_TenantPermissionListRequest.Size(m)
}
func (m *TenantPermissionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantPermissionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TenantPermissionListRequest proto.InternalMessageInfo

func (m *TenantPermissionListRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *TenantPermissionListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *TenantPermissionListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type TenantPermissionListResponse struct {
	Permissions          []*Permission `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Total                int32         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TenantPermissionListResponse) Reset()         { *m = TenantPermissionListResponse{} }
func (m *TenantPermissionListResponse) String() string { return proto.CompactTextString(m) }
func (*TenantPermissionListResponse) ProtoMessage()    {}
func (*TenantPermissionListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{8}
}

func (m *TenantPermissionListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantPermissionListResponse.Unmarshal(m, b)
}
func (m *TenantPermissionListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantPermissionListResponse.Marshal(b, m, deterministic)
}
func (m *TenantPermissionListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantPermissionListResponse.Merge(m, src)
}
func (m *TenantPermissionListResponse) XXX_Size() int {
	return xxx_messageInfo_TenantPermissionListResponse.Size(m)
}
func (m *TenantPermissionListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantPermissionListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TenantPermissionListResponse proto.InternalMessageInfo

func (m *TenantPermissionListResponse) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *TenantPermissionListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type TenantPermissionAssignRequest struct {
	Tenant               string   `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Permission           string   `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	ServiceAccounts      []string `protobuf:"bytes,3,rep,name=service_accounts,json=serviceAccounts,proto3" json:"service_accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantPermissionAssignRequest) Reset()         { *m = TenantPermissionAssignRequest{} }
func (m *TenantPermissionAssignRequest) String() string { return proto.CompactTextString(m) }
func (*TenantPermissionAssignRequest) ProtoMessage()    {}
func (*TenantPermissionAssignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{9}
}

func (m *TenantPermissionAssignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantPermissionAssignRequest.Unmarshal(m, b)
}
func (m *TenantPermissionAssignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantPermissionAssignRequest.Marshal(b, m, deterministic)
}
func (m *TenantPermissionAssignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantPermissionAssignRequest.Merge(m, src)
}
func (m *TenantPermissionAssignRequest) XXX_Size() int {
	return xxx_messageInfo_TenantPermissionAssignRequest.Size(m)
}
func (m *TenantPermissionAssignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantPermissionAssignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TenantPermissionAssignRequest proto.InternalMessageInfo

func (m *TenantPermissionAssignRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *TenantPermissionAssignRequest) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

func (m *TenantPermissionAssignRequest) GetServiceAccounts() []string {
	if m != nil {
		return m.ServiceAccounts
	}
	return nil
}

type TenantPermissionAssignResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantPermissionAssignResponse) Reset()         { *m = TenantPermissionAssignResponse{} }
func (m *TenantPermissionAssignResponse) String() string { return proto.CompactTextString(m) }
func (*TenantPermissionAssignResponse) ProtoMessage()    {}
func (*TenantPermissionAssignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{10}
}

func (m *TenantPermissionAssignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantPermissionAssignResponse.Unmarshal(m, b)
}
func (m *TenantPermissionAssignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantPermissionAssignResponse.Marshal(b, m, deterministic)
}
func (m *TenantPermissionAssignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantPermissionAssignResponse.Merge(m, src)
}
func (m *TenantPermissionAssignResponse) XXX_Size() int {
	return xxx_messageInfo_TenantPermissionAssignResponse.Size(m)
}
func (m *TenantPermissionAssignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantPermissionAssignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TenantPermissionAssignResponse proto.InternalMessageInfo

type TenantUserAddRequest struct {
	Tenant               string   `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Invite               bool     `protobuf:"varint,5,opt,name=invite,proto3" json:"invite,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantUserAddRequest) Reset()         { *m = TenantUserAddRequest{} }
func (m *TenantUserAddRequest) String() string { return proto.CompactTextString(m) }
func (*TenantUserAddRequest) ProtoMessage()    {}
func (*TenantUserAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{11}
}

func (m *TenantUserAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantUserAddRequest.Unmarshal(m, b)
}
func (m *TenantUserAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantUserAddRequest.Marshal(b, m, deterministic)
}
func (m *TenantUserAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantUserAddRequest.Merge(m, src)
}
func (m *TenantUserAddRequest) XXX_Size() int {
	return xxx_messageInfo_TenantUserAddRequest.Size(m)
}
func (m *TenantUserAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantUserAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TenantUserAddRequest proto.InternalMessageInfo

func (m *TenantUserAddRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *TenantUserAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TenantUserAddRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *TenantUserAddRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TenantUserAddRequest) GetInvite() bool {
	if m != nil {
		return m.Invite
	}
	return false
}

type TenantUserAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantUserAddResponse) Reset()         { *m = TenantUserAddResponse{} }
func (m *TenantUserAddResponse) String() string { return proto.CompactTextString(m) }
func (*TenantUserAddResponse) ProtoMessage()    {}
func (*TenantUserAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{12}
}

func (m *TenantUserAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantUserAddResponse.Unmarshal(m, b)
}
func (m *TenantUserAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantUserAddResponse.Marshal(b, m, deterministic)
}
func (m *TenantUserAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantUserAddResponse.Merge(m, src)
}
func (m *TenantUserAddResponse) XXX_Size() int {
	return xxx_messageInfo_TenantUserAddResponse.Size(m)
}
func (m *TenantUserAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantUserAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TenantUserAddResponse proto.InternalMessageInfo

type AdminAddRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminAddRequest) Reset()         { *m = AdminAddRequest{} }
func (m *AdminAddRequest) String() string { return proto.CompactTextString(m) }
func (*AdminAddRequest) ProtoMessage()    {}
func (*AdminAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{13}
}

func (m *AdminAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminAddRequest.Unmarshal(m, b)
}
func (m *AdminAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminAddRequest.Marshal(b, m, deterministic)
}
func (m *AdminAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminAddRequest.Merge(m, src)
}
func (m *AdminAddRequest) XXX_Size() int {
	return xxx_messageInfo_AdminAddRequest.Size(m)
}
func (m *AdminAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminAddRequest proto.InternalMessageInfo

func (m *AdminAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdminAddRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AdminAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminAddResponse) Reset()         { *m = AdminAddResponse{} }
func (m *AdminAddResponse) String() string { return proto.CompactTextString(m) }
func (*AdminAddResponse) ProtoMessage()    {}
func (*AdminAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{14}
}

func (m *AdminAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminAddResponse.Unmarshal(m, b)
}
func (m *AdminAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminAddResponse.Marshal(b, m, deterministic)
}
func (m *AdminAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminAddResponse.Merge(m, src)
}
func (m *AdminAddResponse) XXX_Size() int {
	return xxx_messageInfo_AdminAddResponse.Size(m)
}
func (m *AdminAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminAddResponse proto.InternalMessageInfo

type SetAdminPasswordRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAdminPasswordRequest) Reset()         { *m = SetAdminPasswordRequest{} }
func (m *SetAdminPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*SetAdminPasswordRequest) ProtoMessage()    {}
func (*SetAdminPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{15}
}

func (m *SetAdminPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAdminPasswordRequest.Unmarshal(m, b)
}
func (m *SetAdminPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAdminPasswordRequest.Marshal(b, m, deterministic)
}
func (m *SetAdminPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAdminPasswordRequest.Merge(m, src)
}
func (m *SetAdminPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_SetAdminPasswordRequest.Size(m)
}
func (m *SetAdminPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAdminPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAdminPasswordRequest proto.InternalMessageInfo

func (m *SetAdminPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SetAdminPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SetAdminPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAdminPasswordResponse) Reset()         { *m = SetAdminPasswordResponse{} }
func (m *SetAdminPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*SetAdminPasswordResponse) ProtoMessage()    {}
func (*SetAdminPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{16}
}

func (m *SetAdminPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAdminPasswordResponse.Unmarshal(m, b)
}
func (m *SetAdminPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAdminPasswordResponse.Marshal(b, m, deterministic)
}
func (m *SetAdminPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAdminPasswordResponse.Merge(m, src)
}
func (m *SetAdminPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_SetAdminPasswordResponse.Size(m)
}
func (m *SetAdminPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAdminPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAdminPasswordResponse proto.InternalMessageInfo

type CLILoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLILoginRequest) Reset()         { *m = CLILoginRequest{} }
func (m *CLILoginRequest) String() string { return proto.CompactTextString(m) }
func (*CLILoginRequest) ProtoMessage()    {}
func (*CLILoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{17}
}

func (m *CLILoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLILoginRequest.Unmarshal(m, b)
}
func (m *CLILoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLILoginRequest.Marshal(b, m, deterministic)
}
func (m *CLILoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLILoginRequest.Merge(m, src)
}
func (m *CLILoginRequest) XXX_Size() int {
	return xxx_messageInfo_CLILoginRequest.Size(m)
}
func (m *CLILoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CLILoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CLILoginRequest proto.InternalMessageInfo

func (m *CLILoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CLILoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CLILoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Expires              int64    `protobuf:"varint,2,opt,name=expires,proto3" json:"expires,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RefreshTokenExpires  int64    `protobuf:"varint,4,opt,name=refresh_token_expires,json=refreshTokenExpires,proto3" json:"refresh_token_expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLILoginResponse) Reset()         { *m = CLILoginResponse{} }
func (m *CLILoginResponse) String() string { return proto.CompactTextString(m) }
func (*CLILoginResponse) ProtoMessage()    {}
func (*CLILoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{18}
}

func (m *CLILoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLILoginResponse.Unmarshal(m, b)
}
func (m *CLILoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLILoginResponse.Marshal(b, m, deterministic)
}
func (m *CLILoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLILoginResponse.Merge(m, src)
}
func (m *CLILoginResponse) XXX_Size() int {
	return xxx_messageInfo_CLILoginResponse.Size(m)
}
func (m *CLILoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CLILoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CLILoginResponse proto.InternalMessageInfo

func (m *CLILoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CLILoginResponse) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func (m *CLILoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *CLILoginResponse) GetRefreshTokenExpires() int64 {
	if m != nil {
		return m.RefreshTokenExpires
	}
	return 0
}

type StorageGroupAddRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageGroupAddRequest) Reset()         { *m = StorageGroupAddRequest{} }
func (m *StorageGroupAddRequest) String() string { return proto.CompactTextString(m) }
func (*StorageGroupAddRequest) ProtoMessage()    {}
func (*StorageGroupAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{19}
}

func (m *StorageGroupAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageGroupAddRequest.Unmarshal(m, b)
}
func (m *StorageGroupAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageGroupAddRequest.Marshal(b, m, deterministic)
}
func (m *StorageGroupAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageGroupAddRequest.Merge(m, src)
}
func (m *StorageGroupAddRequest) XXX_Size() int {
	return xxx_messageInfo_StorageGroupAddRequest.Size(m)
}
func (m *StorageGroupAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageGroupAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageGroupAddRequest proto.InternalMessageInfo

func (m *StorageGroupAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StorageGroupAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageGroupAddResponse) Reset()         { *m = StorageGroupAddResponse{} }
func (m *StorageGroupAddResponse) String() string { return proto.CompactTextString(m) }
func (*StorageGroupAddResponse) ProtoMessage()    {}
func (*StorageGroupAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{20}
}

func (m *StorageGroupAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageGroupAddResponse.Unmarshal(m, b)
}
func (m *StorageGroupAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageGroupAddResponse.Marshal(b, m, deterministic)
}
func (m *StorageGroupAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageGroupAddResponse.Merge(m, src)
}
func (m *StorageGroupAddResponse) XXX_Size() int {
	return xxx_messageInfo_StorageGroupAddResponse.Size(m)
}
func (m *StorageGroupAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageGroupAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StorageGroupAddResponse proto.InternalMessageInfo

type TenantUserForgotPasswordRequest struct {
	Tenant               string   `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantUserForgotPasswordRequest) Reset()         { *m = TenantUserForgotPasswordRequest{} }
func (m *TenantUserForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*TenantUserForgotPasswordRequest) ProtoMessage()    {}
func (*TenantUserForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{21}
}

func (m *TenantUserForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantUserForgotPasswordRequest.Unmarshal(m, b)
}
func (m *TenantUserForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantUserForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (m *TenantUserForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantUserForgotPasswordRequest.Merge(m, src)
}
func (m *TenantUserForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_TenantUserForgotPasswordRequest.Size(m)
}
func (m *TenantUserForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantUserForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TenantUserForgotPasswordRequest proto.InternalMessageInfo

func (m *TenantUserForgotPasswordRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *TenantUserForgotPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type TenantUserForgotPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantUserForgotPasswordResponse) Reset()         { *m = TenantUserForgotPasswordResponse{} }
func (m *TenantUserForgotPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*TenantUserForgotPasswordResponse) ProtoMessage()    {}
func (*TenantUserForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{22}
}

func (m *TenantUserForgotPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantUserForgotPasswordResponse.Unmarshal(m, b)
}
func (m *TenantUserForgotPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantUserForgotPasswordResponse.Marshal(b, m, deterministic)
}
func (m *TenantUserForgotPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantUserForgotPasswordResponse.Merge(m, src)
}
func (m *TenantUserForgotPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_TenantUserForgotPasswordResponse.Size(m)
}
func (m *TenantUserForgotPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantUserForgotPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TenantUserForgotPasswordResponse proto.InternalMessageInfo

type TenantServiceAccountActionRequest struct {
	Tenant               string   `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	ServiceAccount       string   `protobuf:"bytes,2,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantServiceAccountActionRequest) Reset()         { *m = TenantServiceAccountActionRequest{} }
func (m *TenantServiceAccountActionRequest) String() string { return proto.CompactTextString(m) }
func (*TenantServiceAccountActionRequest) ProtoMessage()    {}
func (*TenantServiceAccountActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{23}
}

func (m *TenantServiceAccountActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantServiceAccountActionRequest.Unmarshal(m, b)
}
func (m *TenantServiceAccountActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantServiceAccountActionRequest.Marshal(b, m, deterministic)
}
func (m *TenantServiceAccountActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantServiceAccountActionRequest.Merge(m, src)
}
func (m *TenantServiceAccountActionRequest) XXX_Size() int {
	return xxx_messageInfo_TenantServiceAccountActionRequest.Size(m)
}
func (m *TenantServiceAccountActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantServiceAccountActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TenantServiceAccountActionRequest proto.InternalMessageInfo

func (m *TenantServiceAccountActionRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *TenantServiceAccountActionRequest) GetServiceAccount() string {
	if m != nil {
		return m.ServiceAccount
	}
	return ""
}

type TenantServiceAccountActionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantServiceAccountActionResponse) Reset()         { *m = TenantServiceAccountActionResponse{} }
func (m *TenantServiceAccountActionResponse) String() string { return proto.CompactTextString(m) }
func (*TenantServiceAccountActionResponse) ProtoMessage()    {}
func (*TenantServiceAccountActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{24}
}

func (m *TenantServiceAccountActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantServiceAccountActionResponse.Unmarshal(m, b)
}
func (m *TenantServiceAccountActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantServiceAccountActionResponse.Marshal(b, m, deterministic)
}
func (m *TenantServiceAccountActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantServiceAccountActionResponse.Merge(m, src)
}
func (m *TenantServiceAccountActionResponse) XXX_Size() int {
	return xxx_messageInfo_TenantServiceAccountActionResponse.Size(m)
}
func (m *TenantServiceAccountActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantServiceAccountActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TenantServiceAccountActionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AdminEmpty)(nil), "m3.AdminEmpty")
	proto.RegisterType((*TenantAddRequest)(nil), "m3.TenantAddRequest")
	proto.RegisterType((*TenantAddResponse)(nil), "m3.TenantAddResponse")
	proto.RegisterType((*TenantBucketAddRequest)(nil), "m3.TenantBucketAddRequest")
	proto.RegisterType((*TenantBucketAddResponse)(nil), "m3.TenantBucketAddResponse")
	proto.RegisterType((*TenantPermissionAddRequest)(nil), "m3.TenantPermissionAddRequest")
	proto.RegisterType((*TenantPermissionAddResponse)(nil), "m3.TenantPermissionAddResponse")
	proto.RegisterType((*TenantPermissionListRequest)(nil), "m3.TenantPermissionListRequest")
	proto.RegisterType((*TenantPermissionListResponse)(nil), "m3.TenantPermissionListResponse")
	proto.RegisterType((*TenantPermissionAssignRequest)(nil), "m3.TenantPermissionAssignRequest")
	proto.RegisterType((*TenantPermissionAssignResponse)(nil), "m3.TenantPermissionAssignResponse")
	proto.RegisterType((*TenantUserAddRequest)(nil), "m3.TenantUserAddRequest")
	proto.RegisterType((*TenantUserAddResponse)(nil), "m3.TenantUserAddResponse")
	proto.RegisterType((*AdminAddRequest)(nil), "m3.AdminAddRequest")
	proto.RegisterType((*AdminAddResponse)(nil), "m3.AdminAddResponse")
	proto.RegisterType((*SetAdminPasswordRequest)(nil), "m3.SetAdminPasswordRequest")
	proto.RegisterType((*SetAdminPasswordResponse)(nil), "m3.SetAdminPasswordResponse")
	proto.RegisterType((*CLILoginRequest)(nil), "m3.CLILoginRequest")
	proto.RegisterType((*CLILoginResponse)(nil), "m3.CLILoginResponse")
	proto.RegisterType((*StorageGroupAddRequest)(nil), "m3.StorageGroupAddRequest")
	proto.RegisterType((*StorageGroupAddResponse)(nil), "m3.StorageGroupAddResponse")
	proto.RegisterType((*TenantUserForgotPasswordRequest)(nil), "m3.TenantUserForgotPasswordRequest")
	proto.RegisterType((*TenantUserForgotPasswordResponse)(nil), "m3.TenantUserForgotPasswordResponse")
	proto.RegisterType((*TenantServiceAccountActionRequest)(nil), "m3.TenantServiceAccountActionRequest")
	proto.RegisterType((*TenantServiceAccountActionResponse)(nil), "m3.TenantServiceAccountActionResponse")
}

func init() { proto.RegisterFile("private_api.proto", fileDescriptor_f4274b222e5fbd62) }

var fileDescriptor_f4274b222e5fbd62 = []byte{
	// 1001 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdb, 0x6e, 0x1b, 0x45,
	0x18, 0xce, 0xc6, 0x71, 0x62, 0xff, 0x6e, 0x63, 0x77, 0xe2, 0x24, 0xdb, 0xcd, 0xc9, 0x9d, 0x16,
	0x48, 0x39, 0x44, 0x28, 0x41, 0x42, 0x82, 0x2b, 0x27, 0xa4, 0xa8, 0x34, 0x2a, 0xc6, 0x6e, 0x11,
	0x12, 0x17, 0xd6, 0x66, 0x3d, 0x76, 0x47, 0xf5, 0xee, 0x2c, 0x33, 0xe3, 0x40, 0x2f, 0xe1, 0x9a,
	0x37, 0xe0, 0x4d, 0x78, 0x25, 0x5e, 0x02, 0xed, 0xcc, 0xec, 0xd1, 0x6b, 0xbb, 0xea, 0xdd, 0xfe,
	0xa7, 0xef, 0xff, 0x66, 0xe6, 0x3f, 0x2c, 0x3c, 0x08, 0x39, 0xbd, 0x73, 0x25, 0x19, 0xba, 0x21,
	0x3d, 0x0b, 0x39, 0x93, 0x0c, 0xad, 0xfb, 0x17, 0x4e, 0x2b, 0x9c, 0xdd, 0x4e, 0xa9, 0x97, 0x6a,
	0xf1, 0x3d, 0x80, 0xee, 0xc8, 0xa7, 0xc1, 0xb5, 0x1f, 0xca, 0x77, 0xf8, 0x4f, 0x0b, 0x5a, 0xaf,
	0x48, 0xe0, 0x06, 0xb2, 0x3b, 0x1a, 0xf5, 0xc9, 0x6f, 0x33, 0x22, 0x24, 0x42, 0xb0, 0x11, 0xb8,
	0x3e, 0xb1, 0xad, 0x8e, 0x75, 0x5a, 0xef, 0xab, 0x6f, 0x74, 0x04, 0x20, 0xde, 0x30, 0x2e, 0x87,
	0xca, 0xb2, 0xae, 0x2c, 0x75, 0xa5, 0x79, 0x19, 0x99, 0x0f, 0xa0, 0x3e, 0x13, 0x84, 0x6b, 0x6b,
	0x45, 0x59, 0x6b, 0x91, 0xe2, 0xa5, 0x89, 0x55, 0x46, 0xe2, 0xbb, 0x74, 0x6a, 0x6f, 0xe8, 0xd8,
	0x48, 0x73, 0x1d, 0x29, 0xf0, 0x0e, 0x3c, 0xc8, 0x50, 0x10, 0x21, 0x0b, 0x04, 0xc1, 0x3f, 0xc1,
	0x9e, 0x56, 0x5e, 0xce, 0xbc, 0xb7, 0x24, 0xcb, 0x6e, 0x0f, 0x36, 0xa5, 0xb2, 0x18, 0x7e, 0x46,
	0x42, 0x27, 0xd0, 0xb8, 0x55, 0xbe, 0x59, 0x8a, 0xa0, 0x55, 0x11, 0x0d, 0xfc, 0x10, 0xf6, 0xe7,
	0x20, 0x4d, 0xb6, 0x7f, 0x2d, 0x70, 0xb4, 0xad, 0x47, 0xb8, 0x4f, 0x85, 0xa0, 0x2c, 0x78, 0x8f,
	0x94, 0xf1, 0x45, 0xad, 0x67, 0x2e, 0xaa, 0x03, 0x8d, 0x11, 0x11, 0x1e, 0xa7, 0xa1, 0xa4, 0x2c,
	0x30, 0x77, 0x91, 0x55, 0x45, 0x68, 0x64, 0x3c, 0x26, 0x9e, 0x34, 0x57, 0x61, 0x24, 0x74, 0x08,
	0x75, 0x4e, 0x04, 0x9b, 0x71, 0x8f, 0x08, 0xbb, 0xda, 0xa9, 0x44, 0xb7, 0x94, 0x28, 0x90, 0x0d,
	0x5b, 0xae, 0x17, 0xc5, 0x0b, 0x7b, 0x53, 0xd9, 0x62, 0x11, 0x1f, 0xc1, 0x41, 0x29, 0x77, 0x73,
	0x36, 0x6f, 0xde, 0x7c, 0x43, 0x85, 0x5c, 0x75, 0xb6, 0x3d, 0xd8, 0x64, 0xe3, 0xb1, 0x20, 0x52,
	0x9d, 0xae, 0xd2, 0x37, 0x12, 0x6a, 0x43, 0x75, 0x4a, 0x7d, 0x2a, 0xd5, 0xc9, 0xaa, 0x7d, 0x2d,
	0xe0, 0x31, 0x1c, 0x96, 0x27, 0xd1, 0x24, 0xd0, 0x97, 0xd0, 0x08, 0x13, 0x8b, 0xb0, 0xad, 0x4e,
	0xe5, 0xb4, 0x71, 0xbe, 0x7d, 0xe6, 0x5f, 0x9c, 0xa5, 0x01, 0xfd, 0xac, 0x4b, 0x94, 0x47, 0x32,
	0xe9, 0x4e, 0x55, 0xfa, 0x6a, 0x5f, 0x0b, 0xf8, 0x2f, 0x0b, 0x8e, 0xe6, 0x0e, 0x2b, 0x04, 0x9d,
	0x04, 0xab, 0xce, 0x73, 0x0c, 0x90, 0xc2, 0xc7, 0xd5, 0x91, 0x6a, 0xd0, 0x53, 0x68, 0x09, 0xc2,
	0xef, 0xa8, 0x47, 0x86, 0xae, 0xe7, 0xb1, 0x59, 0x20, 0x85, 0x5d, 0x51, 0x17, 0xdd, 0x34, 0xfa,
	0xae, 0x51, 0xe3, 0x0e, 0x1c, 0x2f, 0xe2, 0x60, 0xee, 0xfc, 0x6f, 0x0b, 0xda, 0xda, 0xe5, 0xb5,
	0x20, 0xfc, 0x03, 0x2b, 0xa9, 0x0d, 0x55, 0xdd, 0x31, 0xba, 0x86, 0xb4, 0x80, 0x1c, 0xa8, 0x85,
	0xae, 0x10, 0xbf, 0x33, 0x3e, 0x32, 0xf5, 0x93, 0xc8, 0x11, 0x3a, 0x0d, 0xee, 0xa8, 0x24, 0x76,
	0xb5, 0x63, 0x9d, 0xd6, 0xfa, 0x46, 0xc2, 0xfb, 0xb0, 0x5b, 0x60, 0x63, 0x78, 0x7e, 0x0b, 0x4d,
	0x35, 0x0c, 0x56, 0x34, 0x7f, 0xc2, 0x64, 0x3d, 0xc3, 0x04, 0x23, 0x68, 0xa5, 0xc1, 0x06, 0xf0,
	0x05, 0xec, 0x0f, 0xa2, 0xd6, 0xf2, 0x69, 0xd0, 0x33, 0xac, 0x62, 0x60, 0xf5, 0xa0, 0x6f, 0x49,
	0x60, 0x90, 0xb5, 0x90, 0x3b, 0xce, 0x7a, 0xfe, 0x38, 0xd8, 0x01, 0x7b, 0x1e, 0xcc, 0x24, 0xba,
	0x82, 0xe6, 0xd5, 0xcd, 0xf3, 0x1b, 0x36, 0xa1, 0x41, 0x26, 0x81, 0x66, 0x69, 0x2d, 0xba, 0xaf,
	0x62, 0x82, 0x7f, 0x2c, 0x68, 0xa5, 0x28, 0xa6, 0x54, 0xcb, 0x79, 0xda, 0xb0, 0x45, 0xfe, 0x08,
	0x29, 0x27, 0xc2, 0xf4, 0x43, 0x2c, 0xa2, 0xc7, 0x70, 0x9f, 0x93, 0x31, 0x27, 0xe2, 0xcd, 0x50,
	0xc7, 0xe9, 0xe7, 0xba, 0x67, 0x94, 0xaf, 0x54, 0xf8, 0x39, 0xec, 0xe6, 0x9c, 0x86, 0x31, 0xd8,
	0x86, 0x02, 0xdb, 0xc9, 0x3a, 0x5f, 0x6b, 0x13, 0xfe, 0x1c, 0xf6, 0x06, 0x92, 0x71, 0x77, 0x42,
	0xbe, 0xe7, 0x6c, 0x16, 0x2e, 0x7f, 0xa3, 0x68, 0xba, 0xcd, 0x79, 0x9b, 0xbb, 0xfa, 0x11, 0x4e,
	0xd2, 0xe7, 0x7f, 0xc6, 0xf8, 0x84, 0xc9, 0xe2, 0xe3, 0x2c, 0xaa, 0xcb, 0xf2, 0x97, 0xc7, 0xd0,
	0x59, 0x0c, 0x68, 0x92, 0x8e, 0xe0, 0x91, 0xf6, 0x19, 0xe4, 0xba, 0xa7, 0xab, 0x86, 0xd6, 0xaa,
	0xb4, 0x9f, 0x40, 0xb3, 0xd0, 0x8c, 0x86, 0xc0, 0x76, 0xbe, 0x17, 0xf1, 0x13, 0xc0, 0xcb, 0xb2,
	0x68, 0x2e, 0xe7, 0xff, 0xd5, 0x00, 0x7a, 0x7a, 0x3f, 0x76, 0x7b, 0xcf, 0xd1, 0x53, 0xa8, 0x0e,
	0x88, 0x9c, 0x85, 0x48, 0x0d, 0xa0, 0x74, 0x1b, 0x3a, 0x05, 0x19, 0xaf, 0xa1, 0xcf, 0x60, 0x4b,
	0xb9, 0x7e, 0x77, 0xf9, 0x1e, 0xce, 0xdf, 0x40, 0x3d, 0x59, 0x64, 0xa8, 0x1d, 0x99, 0x8b, 0xab,
	0xd5, 0xd9, 0x2d, 0x68, 0xcd, 0x65, 0xad, 0xa1, 0x1b, 0x68, 0x16, 0x96, 0x13, 0x72, 0x52, 0xdf,
	0xe2, 0x12, 0x74, 0x0e, 0x4a, 0x6d, 0x09, 0xda, 0x2f, 0xb0, 0x53, 0xb2, 0x12, 0xd0, 0x71, 0x1a,
	0x55, 0xb6, 0xe7, 0x9c, 0x93, 0x85, 0xf6, 0x04, 0xf9, 0xd7, 0x78, 0xb0, 0xe5, 0x07, 0x3d, 0x2a,
	0x0d, 0xcd, 0xec, 0x19, 0xa7, 0xb3, 0xd8, 0x21, 0x01, 0x77, 0xe3, 0xa5, 0x5f, 0x1c, 0xac, 0xe8,
	0x51, 0x29, 0xb3, 0xec, 0xe0, 0x77, 0xf0, 0x32, 0x97, 0x24, 0x85, 0x88, 0x4b, 0x37, 0x5f, 0x30,
	0xaf, 0xc3, 0x91, 0x2b, 0x49, 0x8f, 0x4d, 0xa9, 0xf7, 0x0e, 0x7d, 0x94, 0x22, 0x2d, 0x29, 0x5e,
	0xe7, 0xe3, 0x55, 0x6e, 0x49, 0xd2, 0x67, 0x70, 0x3f, 0x37, 0x7f, 0x91, 0x9d, 0x86, 0xe6, 0x17,
	0x84, 0xf3, 0xb0, 0xc4, 0x92, 0xe0, 0x4c, 0xc0, 0x5e, 0xd4, 0x77, 0xe8, 0x71, 0x3e, 0xb0, 0xb4,
	0xcd, 0x9d, 0x27, 0xcb, 0x9d, 0x92, 0x44, 0x5f, 0x43, 0x2d, 0x1e, 0xed, 0x68, 0x27, 0xa9, 0xf3,
	0x0c, 0xcd, 0x76, 0x5e, 0x99, 0x04, 0xfe, 0x00, 0x8d, 0x01, 0x49, 0x49, 0xa9, 0x32, 0x5d, 0xb0,
	0x10, 0x9c, 0xc3, 0x72, 0x63, 0x82, 0xf5, 0x15, 0x54, 0xd5, 0x64, 0xd6, 0x0c, 0x0a, 0xd3, 0x5e,
	0x33, 0x28, 0x0e, 0x6f, 0xbc, 0x86, 0x2e, 0xa0, 0xf9, 0xb3, 0x3b, 0xa5, 0xd1, 0x73, 0x0e, 0x88,
	0x5e, 0xed, 0xab, 0x3b, 0xf7, 0x05, 0x6c, 0x5f, 0x4d, 0x67, 0x42, 0x12, 0x3e, 0xf0, 0x06, 0x93,
	0xa4, 0xf9, 0xca, 0xc7, 0xaf, 0x6e, 0xbe, 0x45, 0xc3, 0x76, 0xed, 0xf2, 0x53, 0xd8, 0xa5, 0xec,
	0xcc, 0xa7, 0x41, 0xe4, 0x66, 0x7e, 0xcb, 0xbf, 0x70, 0x43, 0x7a, 0xd9, 0x8c, 0x67, 0x50, 0x48,
	0x7b, 0xd1, 0xbf, 0x78, 0xcf, 0xba, 0xdd, 0x54, 0x3f, 0xe5, 0x17, 0xff, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x94, 0x3f, 0xf5, 0xc5, 0xbf, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PrivateAPIClient is the client API for PrivateAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrivateAPIClient interface {
	// Setup Operations
	Setup(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminEmpty, error)
	SetupDB(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminEmpty, error)
	// Tenant Operations
	TenantAdd(ctx context.Context, in *TenantAddRequest, opts ...grpc.CallOption) (*TenantAddResponse, error)
	// Tenant Bucket Operations
	TenantBucketAdd(ctx context.Context, in *TenantBucketAddRequest, opts ...grpc.CallOption) (*TenantBucketAddResponse, error)
	// Tenant Permissions Operations
	TenantPermissionAdd(ctx context.Context, in *TenantPermissionAddRequest, opts ...grpc.CallOption) (*TenantPermissionAddResponse, error)
	TenantPermissionList(ctx context.Context, in *TenantPermissionListRequest, opts ...grpc.CallOption) (*TenantPermissionListResponse, error)
	TenantPermissionAssign(ctx context.Context, in *TenantPermissionAssignRequest, opts ...grpc.CallOption) (*TenantPermissionAssignResponse, error)
	// Tenant Service Accounts
	TenantServiceAccountUpdatePolicy(ctx context.Context, in *TenantServiceAccountActionRequest, opts ...grpc.CallOption) (*TenantServiceAccountActionResponse, error)
	// Tenant User Operations
	TenantUserAdd(ctx context.Context, in *TenantUserAddRequest, opts ...grpc.CallOption) (*TenantUserAddResponse, error)
	TenantUserForgotPassword(ctx context.Context, in *TenantUserForgotPasswordRequest, opts ...grpc.CallOption) (*TenantUserForgotPasswordResponse, error)
	// Admin Operations
	AdminAdd(ctx context.Context, in *AdminAddRequest, opts ...grpc.CallOption) (*AdminAddResponse, error)
	SetPassword(ctx context.Context, in *SetAdminPasswordRequest, opts ...grpc.CallOption) (*SetAdminPasswordResponse, error)
	Login(ctx context.Context, in *CLILoginRequest, opts ...grpc.CallOption) (*CLILoginResponse, error)
	// Session related
	ValidateSession(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminEmpty, error)
	// Cluster Operations
	ClusterScSgAdd(ctx context.Context, in *StorageGroupAddRequest, opts ...grpc.CallOption) (*StorageGroupAddResponse, error)
}

type privateAPIClient struct {
	cc *grpc.ClientConn
}

func NewPrivateAPIClient(cc *grpc.ClientConn) PrivateAPIClient {
	return &privateAPIClient{cc}
}

func (c *privateAPIClient) Setup(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminEmpty, error) {
	out := new(AdminEmpty)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/Setup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) SetupDB(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminEmpty, error) {
	out := new(AdminEmpty)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/SetupDB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) TenantAdd(ctx context.Context, in *TenantAddRequest, opts ...grpc.CallOption) (*TenantAddResponse, error) {
	out := new(TenantAddResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/TenantAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) TenantBucketAdd(ctx context.Context, in *TenantBucketAddRequest, opts ...grpc.CallOption) (*TenantBucketAddResponse, error) {
	out := new(TenantBucketAddResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/TenantBucketAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) TenantPermissionAdd(ctx context.Context, in *TenantPermissionAddRequest, opts ...grpc.CallOption) (*TenantPermissionAddResponse, error) {
	out := new(TenantPermissionAddResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/TenantPermissionAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) TenantPermissionList(ctx context.Context, in *TenantPermissionListRequest, opts ...grpc.CallOption) (*TenantPermissionListResponse, error) {
	out := new(TenantPermissionListResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/TenantPermissionList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) TenantPermissionAssign(ctx context.Context, in *TenantPermissionAssignRequest, opts ...grpc.CallOption) (*TenantPermissionAssignResponse, error) {
	out := new(TenantPermissionAssignResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/TenantPermissionAssign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) TenantServiceAccountUpdatePolicy(ctx context.Context, in *TenantServiceAccountActionRequest, opts ...grpc.CallOption) (*TenantServiceAccountActionResponse, error) {
	out := new(TenantServiceAccountActionResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/TenantServiceAccountUpdatePolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) TenantUserAdd(ctx context.Context, in *TenantUserAddRequest, opts ...grpc.CallOption) (*TenantUserAddResponse, error) {
	out := new(TenantUserAddResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/TenantUserAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) TenantUserForgotPassword(ctx context.Context, in *TenantUserForgotPasswordRequest, opts ...grpc.CallOption) (*TenantUserForgotPasswordResponse, error) {
	out := new(TenantUserForgotPasswordResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/TenantUserForgotPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) AdminAdd(ctx context.Context, in *AdminAddRequest, opts ...grpc.CallOption) (*AdminAddResponse, error) {
	out := new(AdminAddResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/AdminAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) SetPassword(ctx context.Context, in *SetAdminPasswordRequest, opts ...grpc.CallOption) (*SetAdminPasswordResponse, error) {
	out := new(SetAdminPasswordResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/SetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) Login(ctx context.Context, in *CLILoginRequest, opts ...grpc.CallOption) (*CLILoginResponse, error) {
	out := new(CLILoginResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) ValidateSession(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminEmpty, error) {
	out := new(AdminEmpty)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/ValidateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) ClusterScSgAdd(ctx context.Context, in *StorageGroupAddRequest, opts ...grpc.CallOption) (*StorageGroupAddResponse, error) {
	out := new(StorageGroupAddResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/ClusterScSgAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivateAPIServer is the server API for PrivateAPI service.
type PrivateAPIServer interface {
	// Setup Operations
	Setup(context.Context, *AdminEmpty) (*AdminEmpty, error)
	SetupDB(context.Context, *AdminEmpty) (*AdminEmpty, error)
	// Tenant Operations
	TenantAdd(context.Context, *TenantAddRequest) (*TenantAddResponse, error)
	// Tenant Bucket Operations
	TenantBucketAdd(context.Context, *TenantBucketAddRequest) (*TenantBucketAddResponse, error)
	// Tenant Permissions Operations
	TenantPermissionAdd(context.Context, *TenantPermissionAddRequest) (*TenantPermissionAddResponse, error)
	TenantPermissionList(context.Context, *TenantPermissionListRequest) (*TenantPermissionListResponse, error)
	TenantPermissionAssign(context.Context, *TenantPermissionAssignRequest) (*TenantPermissionAssignResponse, error)
	// Tenant Service Accounts
	TenantServiceAccountUpdatePolicy(context.Context, *TenantServiceAccountActionRequest) (*TenantServiceAccountActionResponse, error)
	// Tenant User Operations
	TenantUserAdd(context.Context, *TenantUserAddRequest) (*TenantUserAddResponse, error)
	TenantUserForgotPassword(context.Context, *TenantUserForgotPasswordRequest) (*TenantUserForgotPasswordResponse, error)
	// Admin Operations
	AdminAdd(context.Context, *AdminAddRequest) (*AdminAddResponse, error)
	SetPassword(context.Context, *SetAdminPasswordRequest) (*SetAdminPasswordResponse, error)
	Login(context.Context, *CLILoginRequest) (*CLILoginResponse, error)
	// Session related
	ValidateSession(context.Context, *AdminEmpty) (*AdminEmpty, error)
	// Cluster Operations
	ClusterScSgAdd(context.Context, *StorageGroupAddRequest) (*StorageGroupAddResponse, error)
}

// UnimplementedPrivateAPIServer can be embedded to have forward compatible implementations.
type UnimplementedPrivateAPIServer struct {
}

func (*UnimplementedPrivateAPIServer) Setup(ctx context.Context, req *AdminEmpty) (*AdminEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Setup not implemented")
}
func (*UnimplementedPrivateAPIServer) SetupDB(ctx context.Context, req *AdminEmpty) (*AdminEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupDB not implemented")
}
func (*UnimplementedPrivateAPIServer) TenantAdd(ctx context.Context, req *TenantAddRequest) (*TenantAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantAdd not implemented")
}
func (*UnimplementedPrivateAPIServer) TenantBucketAdd(ctx context.Context, req *TenantBucketAddRequest) (*TenantBucketAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantBucketAdd not implemented")
}
func (*UnimplementedPrivateAPIServer) TenantPermissionAdd(ctx context.Context, req *TenantPermissionAddRequest) (*TenantPermissionAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantPermissionAdd not implemented")
}
func (*UnimplementedPrivateAPIServer) TenantPermissionList(ctx context.Context, req *TenantPermissionListRequest) (*TenantPermissionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantPermissionList not implemented")
}
func (*UnimplementedPrivateAPIServer) TenantPermissionAssign(ctx context.Context, req *TenantPermissionAssignRequest) (*TenantPermissionAssignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantPermissionAssign not implemented")
}
func (*UnimplementedPrivateAPIServer) TenantServiceAccountUpdatePolicy(ctx context.Context, req *TenantServiceAccountActionRequest) (*TenantServiceAccountActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantServiceAccountUpdatePolicy not implemented")
}
func (*UnimplementedPrivateAPIServer) TenantUserAdd(ctx context.Context, req *TenantUserAddRequest) (*TenantUserAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantUserAdd not implemented")
}
func (*UnimplementedPrivateAPIServer) TenantUserForgotPassword(ctx context.Context, req *TenantUserForgotPasswordRequest) (*TenantUserForgotPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantUserForgotPassword not implemented")
}
func (*UnimplementedPrivateAPIServer) AdminAdd(ctx context.Context, req *AdminAddRequest) (*AdminAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminAdd not implemented")
}
func (*UnimplementedPrivateAPIServer) SetPassword(ctx context.Context, req *SetAdminPasswordRequest) (*SetAdminPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPassword not implemented")
}
func (*UnimplementedPrivateAPIServer) Login(ctx context.Context, req *CLILoginRequest) (*CLILoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedPrivateAPIServer) ValidateSession(ctx context.Context, req *AdminEmpty) (*AdminEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateSession not implemented")
}
func (*UnimplementedPrivateAPIServer) ClusterScSgAdd(ctx context.Context, req *StorageGroupAddRequest) (*StorageGroupAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterScSgAdd not implemented")
}

func RegisterPrivateAPIServer(s *grpc.Server, srv PrivateAPIServer) {
	s.RegisterService(&_PrivateAPI_serviceDesc, srv)
}

func _PrivateAPI_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).Setup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/Setup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).Setup(ctx, req.(*AdminEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_SetupDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).SetupDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/SetupDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).SetupDB(ctx, req.(*AdminEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_TenantAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).TenantAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/TenantAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).TenantAdd(ctx, req.(*TenantAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_TenantBucketAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantBucketAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).TenantBucketAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/TenantBucketAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).TenantBucketAdd(ctx, req.(*TenantBucketAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_TenantPermissionAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantPermissionAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).TenantPermissionAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/TenantPermissionAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).TenantPermissionAdd(ctx, req.(*TenantPermissionAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_TenantPermissionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantPermissionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).TenantPermissionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/TenantPermissionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).TenantPermissionList(ctx, req.(*TenantPermissionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_TenantPermissionAssign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantPermissionAssignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).TenantPermissionAssign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/TenantPermissionAssign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).TenantPermissionAssign(ctx, req.(*TenantPermissionAssignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_TenantServiceAccountUpdatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantServiceAccountActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).TenantServiceAccountUpdatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/TenantServiceAccountUpdatePolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).TenantServiceAccountUpdatePolicy(ctx, req.(*TenantServiceAccountActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_TenantUserAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantUserAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).TenantUserAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/TenantUserAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).TenantUserAdd(ctx, req.(*TenantUserAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_TenantUserForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantUserForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).TenantUserForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/TenantUserForgotPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).TenantUserForgotPassword(ctx, req.(*TenantUserForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_AdminAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).AdminAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/AdminAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).AdminAdd(ctx, req.(*AdminAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_SetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAdminPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).SetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/SetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).SetPassword(ctx, req.(*SetAdminPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CLILoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).Login(ctx, req.(*CLILoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_ValidateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).ValidateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/ValidateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).ValidateSession(ctx, req.(*AdminEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_ClusterScSgAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageGroupAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).ClusterScSgAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/ClusterScSgAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).ClusterScSgAdd(ctx, req.(*StorageGroupAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PrivateAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "m3.PrivateAPI",
	HandlerType: (*PrivateAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Setup",
			Handler:    _PrivateAPI_Setup_Handler,
		},
		{
			MethodName: "SetupDB",
			Handler:    _PrivateAPI_SetupDB_Handler,
		},
		{
			MethodName: "TenantAdd",
			Handler:    _PrivateAPI_TenantAdd_Handler,
		},
		{
			MethodName: "TenantBucketAdd",
			Handler:    _PrivateAPI_TenantBucketAdd_Handler,
		},
		{
			MethodName: "TenantPermissionAdd",
			Handler:    _PrivateAPI_TenantPermissionAdd_Handler,
		},
		{
			MethodName: "TenantPermissionList",
			Handler:    _PrivateAPI_TenantPermissionList_Handler,
		},
		{
			MethodName: "TenantPermissionAssign",
			Handler:    _PrivateAPI_TenantPermissionAssign_Handler,
		},
		{
			MethodName: "TenantServiceAccountUpdatePolicy",
			Handler:    _PrivateAPI_TenantServiceAccountUpdatePolicy_Handler,
		},
		{
			MethodName: "TenantUserAdd",
			Handler:    _PrivateAPI_TenantUserAdd_Handler,
		},
		{
			MethodName: "TenantUserForgotPassword",
			Handler:    _PrivateAPI_TenantUserForgotPassword_Handler,
		},
		{
			MethodName: "AdminAdd",
			Handler:    _PrivateAPI_AdminAdd_Handler,
		},
		{
			MethodName: "SetPassword",
			Handler:    _PrivateAPI_SetPassword_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _PrivateAPI_Login_Handler,
		},
		{
			MethodName: "ValidateSession",
			Handler:    _PrivateAPI_ValidateSession_Handler,
		},
		{
			MethodName: "ClusterScSgAdd",
			Handler:    _PrivateAPI_ClusterScSgAdd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "private_api.proto",
}
