// Code generated by protoc-gen-go. DO NOT EDIT.
// source: private_api.proto

package m3

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdminEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminEmpty) Reset()         { *m = AdminEmpty{} }
func (m *AdminEmpty) String() string { return proto.CompactTextString(m) }
func (*AdminEmpty) ProtoMessage()    {}
func (*AdminEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{0}
}

func (m *AdminEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminEmpty.Unmarshal(m, b)
}
func (m *AdminEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminEmpty.Marshal(b, m, deterministic)
}
func (m *AdminEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminEmpty.Merge(m, src)
}
func (m *AdminEmpty) XXX_Size() int {
	return xxx_messageInfo_AdminEmpty.Size(m)
}
func (m *AdminEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_AdminEmpty proto.InternalMessageInfo

type TenantAddRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ShortName            string   `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserEmail            string   `protobuf:"bytes,4,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantAddRequest) Reset()         { *m = TenantAddRequest{} }
func (m *TenantAddRequest) String() string { return proto.CompactTextString(m) }
func (*TenantAddRequest) ProtoMessage()    {}
func (*TenantAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{1}
}

func (m *TenantAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantAddRequest.Unmarshal(m, b)
}
func (m *TenantAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantAddRequest.Marshal(b, m, deterministic)
}
func (m *TenantAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantAddRequest.Merge(m, src)
}
func (m *TenantAddRequest) XXX_Size() int {
	return xxx_messageInfo_TenantAddRequest.Size(m)
}
func (m *TenantAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TenantAddRequest proto.InternalMessageInfo

func (m *TenantAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TenantAddRequest) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *TenantAddRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *TenantAddRequest) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

type TenantAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantAddResponse) Reset()         { *m = TenantAddResponse{} }
func (m *TenantAddResponse) String() string { return proto.CompactTextString(m) }
func (*TenantAddResponse) ProtoMessage()    {}
func (*TenantAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{2}
}

func (m *TenantAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantAddResponse.Unmarshal(m, b)
}
func (m *TenantAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantAddResponse.Marshal(b, m, deterministic)
}
func (m *TenantAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantAddResponse.Merge(m, src)
}
func (m *TenantAddResponse) XXX_Size() int {
	return xxx_messageInfo_TenantAddResponse.Size(m)
}
func (m *TenantAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TenantAddResponse proto.InternalMessageInfo

type TenantBucketAddRequest struct {
	Tenant               string   `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	BucketName           string   `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantBucketAddRequest) Reset()         { *m = TenantBucketAddRequest{} }
func (m *TenantBucketAddRequest) String() string { return proto.CompactTextString(m) }
func (*TenantBucketAddRequest) ProtoMessage()    {}
func (*TenantBucketAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{3}
}

func (m *TenantBucketAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantBucketAddRequest.Unmarshal(m, b)
}
func (m *TenantBucketAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantBucketAddRequest.Marshal(b, m, deterministic)
}
func (m *TenantBucketAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantBucketAddRequest.Merge(m, src)
}
func (m *TenantBucketAddRequest) XXX_Size() int {
	return xxx_messageInfo_TenantBucketAddRequest.Size(m)
}
func (m *TenantBucketAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantBucketAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TenantBucketAddRequest proto.InternalMessageInfo

func (m *TenantBucketAddRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *TenantBucketAddRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

type TenantBucketAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantBucketAddResponse) Reset()         { *m = TenantBucketAddResponse{} }
func (m *TenantBucketAddResponse) String() string { return proto.CompactTextString(m) }
func (*TenantBucketAddResponse) ProtoMessage()    {}
func (*TenantBucketAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{4}
}

func (m *TenantBucketAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantBucketAddResponse.Unmarshal(m, b)
}
func (m *TenantBucketAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantBucketAddResponse.Marshal(b, m, deterministic)
}
func (m *TenantBucketAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantBucketAddResponse.Merge(m, src)
}
func (m *TenantBucketAddResponse) XXX_Size() int {
	return xxx_messageInfo_TenantBucketAddResponse.Size(m)
}
func (m *TenantBucketAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantBucketAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TenantBucketAddResponse proto.InternalMessageInfo

type AdminAddRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminAddRequest) Reset()         { *m = AdminAddRequest{} }
func (m *AdminAddRequest) String() string { return proto.CompactTextString(m) }
func (*AdminAddRequest) ProtoMessage()    {}
func (*AdminAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{5}
}

func (m *AdminAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminAddRequest.Unmarshal(m, b)
}
func (m *AdminAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminAddRequest.Marshal(b, m, deterministic)
}
func (m *AdminAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminAddRequest.Merge(m, src)
}
func (m *AdminAddRequest) XXX_Size() int {
	return xxx_messageInfo_AdminAddRequest.Size(m)
}
func (m *AdminAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminAddRequest proto.InternalMessageInfo

func (m *AdminAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdminAddRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AdminAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminAddResponse) Reset()         { *m = AdminAddResponse{} }
func (m *AdminAddResponse) String() string { return proto.CompactTextString(m) }
func (*AdminAddResponse) ProtoMessage()    {}
func (*AdminAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{6}
}

func (m *AdminAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminAddResponse.Unmarshal(m, b)
}
func (m *AdminAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminAddResponse.Marshal(b, m, deterministic)
}
func (m *AdminAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminAddResponse.Merge(m, src)
}
func (m *AdminAddResponse) XXX_Size() int {
	return xxx_messageInfo_AdminAddResponse.Size(m)
}
func (m *AdminAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminAddResponse proto.InternalMessageInfo

type SetAdminPasswordRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAdminPasswordRequest) Reset()         { *m = SetAdminPasswordRequest{} }
func (m *SetAdminPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*SetAdminPasswordRequest) ProtoMessage()    {}
func (*SetAdminPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{7}
}

func (m *SetAdminPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAdminPasswordRequest.Unmarshal(m, b)
}
func (m *SetAdminPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAdminPasswordRequest.Marshal(b, m, deterministic)
}
func (m *SetAdminPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAdminPasswordRequest.Merge(m, src)
}
func (m *SetAdminPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_SetAdminPasswordRequest.Size(m)
}
func (m *SetAdminPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAdminPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAdminPasswordRequest proto.InternalMessageInfo

func (m *SetAdminPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SetAdminPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SetAdminPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAdminPasswordResponse) Reset()         { *m = SetAdminPasswordResponse{} }
func (m *SetAdminPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*SetAdminPasswordResponse) ProtoMessage()    {}
func (*SetAdminPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{8}
}

func (m *SetAdminPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAdminPasswordResponse.Unmarshal(m, b)
}
func (m *SetAdminPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAdminPasswordResponse.Marshal(b, m, deterministic)
}
func (m *SetAdminPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAdminPasswordResponse.Merge(m, src)
}
func (m *SetAdminPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_SetAdminPasswordResponse.Size(m)
}
func (m *SetAdminPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAdminPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAdminPasswordResponse proto.InternalMessageInfo

type CLILoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLILoginRequest) Reset()         { *m = CLILoginRequest{} }
func (m *CLILoginRequest) String() string { return proto.CompactTextString(m) }
func (*CLILoginRequest) ProtoMessage()    {}
func (*CLILoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{9}
}

func (m *CLILoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLILoginRequest.Unmarshal(m, b)
}
func (m *CLILoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLILoginRequest.Marshal(b, m, deterministic)
}
func (m *CLILoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLILoginRequest.Merge(m, src)
}
func (m *CLILoginRequest) XXX_Size() int {
	return xxx_messageInfo_CLILoginRequest.Size(m)
}
func (m *CLILoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CLILoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CLILoginRequest proto.InternalMessageInfo

func (m *CLILoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CLILoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CLILoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Expires              int64    `protobuf:"varint,2,opt,name=expires,proto3" json:"expires,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RefreshTokenExpires  int64    `protobuf:"varint,4,opt,name=refresh_token_expires,json=refreshTokenExpires,proto3" json:"refresh_token_expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLILoginResponse) Reset()         { *m = CLILoginResponse{} }
func (m *CLILoginResponse) String() string { return proto.CompactTextString(m) }
func (*CLILoginResponse) ProtoMessage()    {}
func (*CLILoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{10}
}

func (m *CLILoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLILoginResponse.Unmarshal(m, b)
}
func (m *CLILoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLILoginResponse.Marshal(b, m, deterministic)
}
func (m *CLILoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLILoginResponse.Merge(m, src)
}
func (m *CLILoginResponse) XXX_Size() int {
	return xxx_messageInfo_CLILoginResponse.Size(m)
}
func (m *CLILoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CLILoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CLILoginResponse proto.InternalMessageInfo

func (m *CLILoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CLILoginResponse) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func (m *CLILoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *CLILoginResponse) GetRefreshTokenExpires() int64 {
	if m != nil {
		return m.RefreshTokenExpires
	}
	return 0
}

type StorageGroupAddRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageGroupAddRequest) Reset()         { *m = StorageGroupAddRequest{} }
func (m *StorageGroupAddRequest) String() string { return proto.CompactTextString(m) }
func (*StorageGroupAddRequest) ProtoMessage()    {}
func (*StorageGroupAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{11}
}

func (m *StorageGroupAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageGroupAddRequest.Unmarshal(m, b)
}
func (m *StorageGroupAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageGroupAddRequest.Marshal(b, m, deterministic)
}
func (m *StorageGroupAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageGroupAddRequest.Merge(m, src)
}
func (m *StorageGroupAddRequest) XXX_Size() int {
	return xxx_messageInfo_StorageGroupAddRequest.Size(m)
}
func (m *StorageGroupAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageGroupAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageGroupAddRequest proto.InternalMessageInfo

func (m *StorageGroupAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StorageGroupAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageGroupAddResponse) Reset()         { *m = StorageGroupAddResponse{} }
func (m *StorageGroupAddResponse) String() string { return proto.CompactTextString(m) }
func (*StorageGroupAddResponse) ProtoMessage()    {}
func (*StorageGroupAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4274b222e5fbd62, []int{12}
}

func (m *StorageGroupAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageGroupAddResponse.Unmarshal(m, b)
}
func (m *StorageGroupAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageGroupAddResponse.Marshal(b, m, deterministic)
}
func (m *StorageGroupAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageGroupAddResponse.Merge(m, src)
}
func (m *StorageGroupAddResponse) XXX_Size() int {
	return xxx_messageInfo_StorageGroupAddResponse.Size(m)
}
func (m *StorageGroupAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageGroupAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StorageGroupAddResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AdminEmpty)(nil), "m3.AdminEmpty")
	proto.RegisterType((*TenantAddRequest)(nil), "m3.TenantAddRequest")
	proto.RegisterType((*TenantAddResponse)(nil), "m3.TenantAddResponse")
	proto.RegisterType((*TenantBucketAddRequest)(nil), "m3.TenantBucketAddRequest")
	proto.RegisterType((*TenantBucketAddResponse)(nil), "m3.TenantBucketAddResponse")
	proto.RegisterType((*AdminAddRequest)(nil), "m3.AdminAddRequest")
	proto.RegisterType((*AdminAddResponse)(nil), "m3.AdminAddResponse")
	proto.RegisterType((*SetAdminPasswordRequest)(nil), "m3.SetAdminPasswordRequest")
	proto.RegisterType((*SetAdminPasswordResponse)(nil), "m3.SetAdminPasswordResponse")
	proto.RegisterType((*CLILoginRequest)(nil), "m3.CLILoginRequest")
	proto.RegisterType((*CLILoginResponse)(nil), "m3.CLILoginResponse")
	proto.RegisterType((*StorageGroupAddRequest)(nil), "m3.StorageGroupAddRequest")
	proto.RegisterType((*StorageGroupAddResponse)(nil), "m3.StorageGroupAddResponse")
}

func init() { proto.RegisterFile("private_api.proto", fileDescriptor_f4274b222e5fbd62) }

var fileDescriptor_f4274b222e5fbd62 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4b, 0x6f, 0xda, 0x40,
	0x10, 0xc6, 0x01, 0x12, 0x98, 0xa4, 0x81, 0x2c, 0x8f, 0x50, 0xa7, 0x55, 0xab, 0xed, 0xa5, 0x4f,
	0x0e, 0xa1, 0x52, 0xa5, 0xf6, 0x04, 0x14, 0x55, 0x69, 0x50, 0x44, 0x71, 0xee, 0xc8, 0x09, 0x5b,
	0xb2, 0x4a, 0x6c, 0x6f, 0x77, 0xd7, 0x7d, 0x1c, 0xfb, 0x3b, 0xfa, 0x3f, 0x7b, 0xae, 0xf6, 0x61,
	0xe3, 0x18, 0x48, 0x73, 0xf3, 0xcc, 0x37, 0xf3, 0xcd, 0xe7, 0xdd, 0x6f, 0x16, 0x0e, 0x18, 0xa7,
	0xdf, 0x7d, 0x49, 0x66, 0x3e, 0xa3, 0x5d, 0xc6, 0x23, 0x19, 0xa1, 0xad, 0xa0, 0x87, 0xf7, 0x00,
	0xfa, 0xf3, 0x80, 0x86, 0xa3, 0x80, 0xc9, 0x5f, 0xf8, 0xb7, 0x03, 0xf5, 0x73, 0x12, 0xfa, 0xa1,
	0xec, 0xcf, 0xe7, 0x53, 0xf2, 0x2d, 0x26, 0x42, 0x22, 0x04, 0xa5, 0xd0, 0x0f, 0x48, 0xc7, 0x79,
	0xea, 0x3c, 0xaf, 0x4e, 0xf5, 0x37, 0x7a, 0x0c, 0x20, 0xae, 0x22, 0x2e, 0x67, 0x1a, 0xd9, 0xd2,
	0x48, 0x55, 0x67, 0xce, 0x14, 0x7c, 0x04, 0xd5, 0x58, 0x10, 0x6e, 0xd0, 0xa2, 0x46, 0x2b, 0x2a,
	0x71, 0x66, 0x7b, 0x35, 0x48, 0x02, 0x9f, 0xde, 0x74, 0x4a, 0xa6, 0x57, 0x65, 0x46, 0x2a, 0x81,
	0x1b, 0x70, 0x90, 0x91, 0x20, 0x58, 0x14, 0x0a, 0x82, 0xbf, 0x40, 0xdb, 0x24, 0x07, 0xf1, 0xe5,
	0x35, 0xc9, 0xaa, 0x6b, 0xc3, 0xb6, 0xd4, 0x88, 0xd5, 0x67, 0x23, 0xf4, 0x04, 0x76, 0x2f, 0x74,
	0x6d, 0x56, 0x22, 0x98, 0x94, 0x92, 0x81, 0x1f, 0xc2, 0xe1, 0x0a, 0xa5, 0x9d, 0xf6, 0x01, 0x6a,
	0xfa, 0x50, 0xfe, 0x73, 0x08, 0x4d, 0x28, 0x9b, 0x7f, 0x30, 0xe4, 0x26, 0xc0, 0x08, 0xea, 0xcb,
	0x66, 0x4b, 0x78, 0x0a, 0x87, 0x9e, 0x1a, 0x11, 0xd0, 0x70, 0xe2, 0x0b, 0xf1, 0x23, 0xe2, 0x29,
	0x71, 0x13, 0xca, 0x32, 0xba, 0x26, 0xa1, 0x65, 0x36, 0x01, 0x72, 0xa1, 0xc2, 0x6c, 0xa1, 0x65,
	0x4f, 0x63, 0xec, 0x42, 0x67, 0x95, 0xcc, 0x0e, 0x1a, 0x42, 0x6d, 0x38, 0x3e, 0x19, 0x47, 0x0b,
	0x1a, 0x66, 0x06, 0x18, 0x95, 0x4e, 0x46, 0xe5, 0x9d, 0x03, 0xfe, 0x38, 0x50, 0x5f, 0xb2, 0x18,
	0xe6, 0x0d, 0x3a, 0x3b, 0xb0, 0x43, 0x7e, 0x32, 0xca, 0x89, 0xd0, 0x2c, 0xc5, 0x69, 0x12, 0xa2,
	0x67, 0xf0, 0x80, 0x93, 0xaf, 0x9c, 0x88, 0xab, 0x99, 0xe9, 0x33, 0x36, 0xd8, 0xb3, 0xc9, 0x73,
	0xdd, 0x7e, 0x0c, 0xad, 0x5b, 0x45, 0xb3, 0x84, 0xac, 0xa4, 0xc9, 0x1a, 0xd9, 0xe2, 0x91, 0x81,
	0xf0, 0x6b, 0x68, 0x7b, 0x32, 0xe2, 0xfe, 0x82, 0x7c, 0xe2, 0x51, 0xcc, 0xee, 0xbe, 0x23, 0x75,
	0xcb, 0x2b, 0xd5, 0xe6, 0x8f, 0x8e, 0xff, 0x16, 0x01, 0x26, 0x66, 0x29, 0xfa, 0x93, 0x13, 0xf4,
	0x02, 0xca, 0x1e, 0x91, 0x31, 0x43, 0xfb, 0xdd, 0xa0, 0xd7, 0x5d, 0x2e, 0x85, 0x9b, 0x8b, 0x71,
	0x01, 0xbd, 0x82, 0x1d, 0x5d, 0xfa, 0x71, 0x70, 0x8f, 0xe2, 0xf7, 0x50, 0x4d, 0xfd, 0x8c, 0x9a,
	0x0a, 0xce, 0x6f, 0x98, 0xdb, 0xca, 0x65, 0xed, 0x65, 0x16, 0xd0, 0x18, 0x6a, 0x39, 0x8f, 0x22,
	0x77, 0x59, 0x9b, 0xdf, 0x05, 0xf7, 0x68, 0x2d, 0x96, 0xb2, 0xbd, 0x83, 0x4a, 0xe2, 0x4c, 0xd4,
	0x48, 0x75, 0x66, 0xfa, 0x9b, 0xb7, 0x93, 0x69, 0xe3, 0x67, 0xd8, 0xf5, 0x88, 0x4c, 0xcc, 0x86,
	0xf4, 0x98, 0x0d, 0x7e, 0x76, 0x1f, 0xad, 0x07, 0x53, 0xae, 0xb7, 0x50, 0xd6, 0xc6, 0x32, 0x0a,
	0x72, 0x66, 0x35, 0x0a, 0xf2, 0xde, 0xc3, 0x05, 0x74, 0x0a, 0xfb, 0xc3, 0x9b, 0x58, 0x48, 0xc2,
	0xbd, 0x4b, 0x6f, 0x91, 0x9e, 0xc3, 0x7a, 0x23, 0x98, 0x73, 0xd8, 0x70, 0xed, 0xb8, 0x30, 0x78,
	0x09, 0x2d, 0x1a, 0x75, 0x03, 0x1a, 0xaa, 0x32, 0xfb, 0x2c, 0xbe, 0xf1, 0x19, 0x1d, 0xd4, 0x12,
	0x3b, 0x30, 0x3a, 0x51, 0x2f, 0xe4, 0xc4, 0xb9, 0xd8, 0xd6, 0x4f, 0x65, 0xef, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x63, 0xe6, 0xfa, 0x3e, 0x3f, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PrivateAPIClient is the client API for PrivateAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrivateAPIClient interface {
	// Setup Operations
	Setup(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminEmpty, error)
	SetupDB(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminEmpty, error)
	// Tenant Operations
	TenantAdd(ctx context.Context, in *TenantAddRequest, opts ...grpc.CallOption) (*TenantAddResponse, error)
	// Tenant Bucket Operations
	TenantBucketAdd(ctx context.Context, in *TenantBucketAddRequest, opts ...grpc.CallOption) (*TenantBucketAddResponse, error)
	// Admin Operations
	AdminAdd(ctx context.Context, in *AdminAddRequest, opts ...grpc.CallOption) (*AdminAddResponse, error)
	SetPassword(ctx context.Context, in *SetAdminPasswordRequest, opts ...grpc.CallOption) (*SetAdminPasswordResponse, error)
	Login(ctx context.Context, in *CLILoginRequest, opts ...grpc.CallOption) (*CLILoginResponse, error)
	// Cluster Operations
	ClusterScSgAdd(ctx context.Context, in *StorageGroupAddRequest, opts ...grpc.CallOption) (*StorageGroupAddResponse, error)
}

type privateAPIClient struct {
	cc *grpc.ClientConn
}

func NewPrivateAPIClient(cc *grpc.ClientConn) PrivateAPIClient {
	return &privateAPIClient{cc}
}

func (c *privateAPIClient) Setup(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminEmpty, error) {
	out := new(AdminEmpty)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/Setup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) SetupDB(ctx context.Context, in *AdminEmpty, opts ...grpc.CallOption) (*AdminEmpty, error) {
	out := new(AdminEmpty)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/SetupDB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) TenantAdd(ctx context.Context, in *TenantAddRequest, opts ...grpc.CallOption) (*TenantAddResponse, error) {
	out := new(TenantAddResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/TenantAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) TenantBucketAdd(ctx context.Context, in *TenantBucketAddRequest, opts ...grpc.CallOption) (*TenantBucketAddResponse, error) {
	out := new(TenantBucketAddResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/TenantBucketAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) AdminAdd(ctx context.Context, in *AdminAddRequest, opts ...grpc.CallOption) (*AdminAddResponse, error) {
	out := new(AdminAddResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/AdminAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) SetPassword(ctx context.Context, in *SetAdminPasswordRequest, opts ...grpc.CallOption) (*SetAdminPasswordResponse, error) {
	out := new(SetAdminPasswordResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/SetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) Login(ctx context.Context, in *CLILoginRequest, opts ...grpc.CallOption) (*CLILoginResponse, error) {
	out := new(CLILoginResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateAPIClient) ClusterScSgAdd(ctx context.Context, in *StorageGroupAddRequest, opts ...grpc.CallOption) (*StorageGroupAddResponse, error) {
	out := new(StorageGroupAddResponse)
	err := c.cc.Invoke(ctx, "/m3.PrivateAPI/ClusterScSgAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivateAPIServer is the server API for PrivateAPI service.
type PrivateAPIServer interface {
	// Setup Operations
	Setup(context.Context, *AdminEmpty) (*AdminEmpty, error)
	SetupDB(context.Context, *AdminEmpty) (*AdminEmpty, error)
	// Tenant Operations
	TenantAdd(context.Context, *TenantAddRequest) (*TenantAddResponse, error)
	// Tenant Bucket Operations
	TenantBucketAdd(context.Context, *TenantBucketAddRequest) (*TenantBucketAddResponse, error)
	// Admin Operations
	AdminAdd(context.Context, *AdminAddRequest) (*AdminAddResponse, error)
	SetPassword(context.Context, *SetAdminPasswordRequest) (*SetAdminPasswordResponse, error)
	Login(context.Context, *CLILoginRequest) (*CLILoginResponse, error)
	// Cluster Operations
	ClusterScSgAdd(context.Context, *StorageGroupAddRequest) (*StorageGroupAddResponse, error)
}

// UnimplementedPrivateAPIServer can be embedded to have forward compatible implementations.
type UnimplementedPrivateAPIServer struct {
}

func (*UnimplementedPrivateAPIServer) Setup(ctx context.Context, req *AdminEmpty) (*AdminEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Setup not implemented")
}
func (*UnimplementedPrivateAPIServer) SetupDB(ctx context.Context, req *AdminEmpty) (*AdminEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupDB not implemented")
}
func (*UnimplementedPrivateAPIServer) TenantAdd(ctx context.Context, req *TenantAddRequest) (*TenantAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantAdd not implemented")
}
func (*UnimplementedPrivateAPIServer) TenantBucketAdd(ctx context.Context, req *TenantBucketAddRequest) (*TenantBucketAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantBucketAdd not implemented")
}
func (*UnimplementedPrivateAPIServer) AdminAdd(ctx context.Context, req *AdminAddRequest) (*AdminAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminAdd not implemented")
}
func (*UnimplementedPrivateAPIServer) SetPassword(ctx context.Context, req *SetAdminPasswordRequest) (*SetAdminPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPassword not implemented")
}
func (*UnimplementedPrivateAPIServer) Login(ctx context.Context, req *CLILoginRequest) (*CLILoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedPrivateAPIServer) ClusterScSgAdd(ctx context.Context, req *StorageGroupAddRequest) (*StorageGroupAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterScSgAdd not implemented")
}

func RegisterPrivateAPIServer(s *grpc.Server, srv PrivateAPIServer) {
	s.RegisterService(&_PrivateAPI_serviceDesc, srv)
}

func _PrivateAPI_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).Setup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/Setup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).Setup(ctx, req.(*AdminEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_SetupDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).SetupDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/SetupDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).SetupDB(ctx, req.(*AdminEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_TenantAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).TenantAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/TenantAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).TenantAdd(ctx, req.(*TenantAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_TenantBucketAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantBucketAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).TenantBucketAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/TenantBucketAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).TenantBucketAdd(ctx, req.(*TenantBucketAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_AdminAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).AdminAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/AdminAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).AdminAdd(ctx, req.(*AdminAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_SetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAdminPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).SetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/SetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).SetPassword(ctx, req.(*SetAdminPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CLILoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).Login(ctx, req.(*CLILoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateAPI_ClusterScSgAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageGroupAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateAPIServer).ClusterScSgAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3.PrivateAPI/ClusterScSgAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateAPIServer).ClusterScSgAdd(ctx, req.(*StorageGroupAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PrivateAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "m3.PrivateAPI",
	HandlerType: (*PrivateAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Setup",
			Handler:    _PrivateAPI_Setup_Handler,
		},
		{
			MethodName: "SetupDB",
			Handler:    _PrivateAPI_SetupDB_Handler,
		},
		{
			MethodName: "TenantAdd",
			Handler:    _PrivateAPI_TenantAdd_Handler,
		},
		{
			MethodName: "TenantBucketAdd",
			Handler:    _PrivateAPI_TenantBucketAdd_Handler,
		},
		{
			MethodName: "AdminAdd",
			Handler:    _PrivateAPI_AdminAdd_Handler,
		},
		{
			MethodName: "SetPassword",
			Handler:    _PrivateAPI_SetPassword_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _PrivateAPI_Login_Handler,
		},
		{
			MethodName: "ClusterScSgAdd",
			Handler:    _PrivateAPI_ClusterScSgAdd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "private_api.proto",
}
