apiVersion: apps/v1
kind: Deployment
metadata:
  name: m3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m3
  template:
    metadata:
      labels:
        app: m3
    spec:
      serviceAccountName: m3-sa
      containers:
        - name: m3
          image: minio/m3:edge
          imagePullPolicy: "IfNotPresent"
          args:
            - /m3
            - server
          envFrom:
            - configMapRef:
                name: m3-env
          ports:
            - containerPort: 8787
              name: http
            - containerPort: 8443
              name: https
