name: Go

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    name: Test on Go ${{ matrix.go-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.13.x]
        os: [ubuntu-latest]
    steps:
      - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
     
      - name: Build on ${{ matrix.os }}
        env:
          GO111MODULE: on
        run: |
          diff -au <(gofmt -d *.go) <(printf "")
          diff -au <(gofmt -d cmd) <(printf "")
          diff -au <(gofmt -d pkg) <(printf "")
          go test -v -race ./...
