// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Kubernetes Cloud
// Copyright (c) 2020 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StartMirroringResponse start mirroring response
//
// swagger:model startMirroringResponse
type StartMirroringResponse struct {

	// mirror id
	// Required: true
	MirrorID *string `json:"mirror_id"`
}

// Validate validates this start mirroring response
func (m *StartMirroringResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMirrorID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StartMirroringResponse) validateMirrorID(formats strfmt.Registry) error {

	if err := validate.Required("mirror_id", "body", m.MirrorID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StartMirroringResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StartMirroringResponse) UnmarshalBinary(b []byte) error {
	var res StartMirroringResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
